-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- permdock helpers (database: reads the membership and user_roles tables)
-- policies call them uncorrelated, so Postgres evaluates each once per statement

create schema if not exists "permdock";
revoke all on schema "permdock" from public;
grant usage on schema "permdock" to authenticated;

create table if not exists "permdock".role_permissions (
  role text not null,
  permission text not null,
  grant_key text not null,
  scope text not null check (scope ~ '^[a-z][a-z0-9_]*$'),
  effect text not null default 'allow' check (effect in ('allow', 'deny')),
  primary key (role, grant_key, scope)
);
alter table "permdock".role_permissions enable row level security;
revoke all on table "permdock".role_permissions from anon, authenticated, public;

create table if not exists "permdock".user_roles (
  user_id uuid not null references auth.users on delete cascade,
  role text not null,
  primary key (user_id, role)
);
alter table "permdock".user_roles enable row level security;
revoke all on table "permdock".user_roles from anon, authenticated, public;

create or replace function "permdock".permdock_has(p_grant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from "permdock".user_roles ur
    join "permdock".role_permissions rp on rp.role = ur.role::text
    where ur.user_id = (select auth.uid())
      and rp.grant_key = p_grant
      and rp.scope = 'global'
  )
$$;
revoke execute on function "permdock".permdock_has(text) from public, anon;
grant execute on function "permdock".permdock_has(text) to authenticated;

create or replace function "permdock".permitted_organization_ids(p_grant text)
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := (select auth.uid());
begin
  return query
  select (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
  ) ms
  cross join lateral jsonb_array_elements_text(
    case jsonb_typeof(ms.roles) when 'array' then ms.roles else '[]'::jsonb end
  ) r(role)
  join "permdock".role_permissions rp on rp.role = r.role
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'organization'
    and rp.grant_key = p_grant
    and rp.scope = 'organization'
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or ms.id = nullif(((select auth.jwt()) ->> 'tenant_id'), ''));
end;
$$;
revoke execute on function "permdock".permitted_organization_ids(text) from public, anon;
grant execute on function "permdock".permitted_organization_ids(text) to authenticated;

create or replace function "permdock".member_organization_ids()
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := (select auth.uid());
begin
  return query
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
  ) ms
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'organization'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0;
end;
$$;
revoke execute on function "permdock".member_organization_ids() from public, anon;
grant execute on function "permdock".member_organization_ids() to authenticated;

create or replace function "permdock".member_organization_ids_for(p_user uuid)
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := p_user;
begin
  return query
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
  ) ms
  where coalesce(p_user::text, '') <> ''
    and ms.scope = 'organization'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0;
end;
$$;
revoke execute on function "permdock".member_organization_ids_for(uuid) from public, anon, authenticated;

create or replace function "permdock".permitted_customer_ids(p_grant text)
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := (select auth.uid());
  v_user_1 "public"."contacts"."user_id"%type := (select auth.uid());
begin
  return query
  select (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
    union all
    select 'customer'::text as scope, m."customer_id"::text as id, jsonb_build_object('organization', m."organization_id"::text) as within, jsonb_build_array('contact') as roles, 'contact'::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."contacts" m
    where m."user_id" = v_user_1
    group by m."customer_id", m."organization_id"
  ) ms
  cross join lateral jsonb_array_elements_text(
    case jsonb_typeof(ms.roles) when 'array' then ms.roles else '[]'::jsonb end
  ) r(role)
  join "permdock".role_permissions rp on rp.role = r.role
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'customer'
    and rp.grant_key = p_grant
    and rp.scope = 'customer'
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or ms.within ->> 'organization' = nullif(((select auth.jwt()) ->> 'tenant_id'), ''));
end;
$$;
revoke execute on function "permdock".permitted_customer_ids(text) from public, anon;
grant execute on function "permdock".permitted_customer_ids(text) to authenticated;

create or replace function "permdock".member_customer_ids()
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := (select auth.uid());
  v_user_1 "public"."contacts"."user_id"%type := (select auth.uid());
begin
  return query
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
    union all
    select 'customer'::text as scope, m."customer_id"::text as id, jsonb_build_object('organization', m."organization_id"::text) as within, jsonb_build_array('contact') as roles, 'contact'::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."contacts" m
    where m."user_id" = v_user_1
    group by m."customer_id", m."organization_id"
  ) ms
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'customer'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0;
end;
$$;
revoke execute on function "permdock".member_customer_ids() from public, anon;
grant execute on function "permdock".member_customer_ids() to authenticated;

create or replace function "permdock".member_customer_ids_for(p_user uuid)
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := p_user;
  v_user_1 "public"."contacts"."user_id"%type := p_user;
begin
  return query
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
    union all
    select 'customer'::text as scope, m."customer_id"::text as id, jsonb_build_object('organization', m."organization_id"::text) as within, jsonb_build_array('contact') as roles, 'contact'::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."contacts" m
    where m."user_id" = v_user_1
    group by m."customer_id", m."organization_id"
  ) ms
  where coalesce(p_user::text, '') <> ''
    and ms.scope = 'customer'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0;
end;
$$;
revoke execute on function "permdock".member_customer_ids_for(uuid) from public, anon, authenticated;

-- the helpers for a user the caller names: trusted SQL acting for a stored user; no client role may execute them
create or replace function "permdock".permdock_has_for(p_user uuid, p_grant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from "permdock".user_roles ur
    join "permdock".role_permissions rp on rp.role = ur.role::text
    where ur.user_id = p_user
      and rp.grant_key = p_grant
      and rp.scope = 'global'
  )
$$;
revoke execute on function "permdock".permdock_has_for(uuid, text) from public, anon, authenticated;

create or replace function "permdock".permitted_organization_ids_for(p_user uuid, p_grant text)
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := p_user;
begin
  return query
  select (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
  ) ms
  cross join lateral jsonb_array_elements_text(
    case jsonb_typeof(ms.roles) when 'array' then ms.roles else '[]'::jsonb end
  ) r(role)
  join "permdock".role_permissions rp on rp.role = r.role
  where coalesce(p_user::text, '') <> ''
    and ms.scope = 'organization'
    and rp.grant_key = p_grant
    and rp.scope = 'organization';
end;
$$;
revoke execute on function "permdock".permitted_organization_ids_for(uuid, text) from public, anon, authenticated;

create or replace function "permdock".permitted_customer_ids_for(p_user uuid, p_grant text)
returns setof uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_0 "public"."memberships"."user_id"%type := p_user;
  v_user_1 "public"."contacts"."user_id"%type := p_user;
begin
  return query
  select (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id" = v_user_0
    group by m."scope"::text, m."scope_id"::text
    union all
    select 'customer'::text as scope, m."customer_id"::text as id, jsonb_build_object('organization', m."organization_id"::text) as within, jsonb_build_array('contact') as roles, 'contact'::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."contacts" m
    where m."user_id" = v_user_1
    group by m."customer_id", m."organization_id"
  ) ms
  cross join lateral jsonb_array_elements_text(
    case jsonb_typeof(ms.roles) when 'array' then ms.roles else '[]'::jsonb end
  ) r(role)
  join "permdock".role_permissions rp on rp.role = r.role
  where coalesce(p_user::text, '') <> ''
    and ms.scope = 'customer'
    and rp.grant_key = p_grant
    and rp.scope = 'customer';
end;
$$;
revoke execute on function "permdock".permitted_customer_ids_for(uuid, text) from public, anon, authenticated;

-- the grant keys a permission key reaches on one scope: its unconditional allows, with p_effect 'deny' every deny, and with 'conditioned-allow' or 'conditioned-deny' the allows or denies that carry a row condition
create or replace function "permdock".grant_keys(p_permission text, p_scope text, p_effect text default 'allow')
returns setof text
language sql
stable
set search_path = ''
as $$
  select g.grant_key
  from pg_catalog.jsonb_array_elements_text(coalesce(
    '{"customer":{"quotes.list":{"allow":["quotes.list"],"deny":[]},"quotes.read":{"allow":["quotes.read"],"deny":[]}},"organization":{"quotes.list":{"allow":["quotes.list"],"deny":[]},"quotes.read":{"allow":["quotes.read"],"deny":[]},"quotes.update":{"allow":["quotes.update"],"deny":[]},"staff.list":{"allow":["staff.list"],"deny":[]},"staff.read":{"allow":["staff.read"],"deny":[]}}}'::jsonb -> p_scope -> p_permission -> p_effect,
    '[]'::jsonb
  )) g(grant_key)
$$;
revoke execute on function "permdock".grant_keys(text, text, text) from public, anon;
grant execute on function "permdock".grant_keys(text, text, text) to authenticated;

-- the helpers by permission key: unconditional allows minus any deny
create or replace function "permdock".permdock_has_permission(p_permission text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from "permdock".grant_keys(p_permission, 'global') g(grant_key) where "permdock".permdock_has(g.grant_key))
    and not exists (select 1 from "permdock".grant_keys(p_permission, 'global', 'deny') g(grant_key) where "permdock".permdock_has(g.grant_key))
$$;
revoke execute on function "permdock".permdock_has_permission(text) from public, anon;
grant execute on function "permdock".permdock_has_permission(text) to authenticated;

create or replace function "permdock".permitted_organization_ids_by_permission(p_permission text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from "permdock".grant_keys(p_permission, 'organization') g(grant_key)
  cross join lateral "permdock".permitted_organization_ids(g.grant_key) a(id)
  except
  select d.id
  from "permdock".grant_keys(p_permission, 'organization', 'deny') g(grant_key)
  cross join lateral "permdock".permitted_organization_ids(g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_organization_ids_by_permission(text) from public, anon;
grant execute on function "permdock".permitted_organization_ids_by_permission(text) to authenticated;

-- with p_conditioned true, also the instances a conditioned allow reaches, minus only unconditional denies: the caller applies the row condition
create or replace function "permdock".permitted_organization_ids_by_permission(p_permission text, p_conditioned boolean)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization') g(grant_key)
    union all
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization', 'conditioned-allow') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_organization_ids(g.grant_key) a(id)
  except
  select d.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization', 'deny') g(grant_key)
    except
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization', 'conditioned-deny') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_organization_ids(g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_organization_ids_by_permission(text, boolean) from public, anon;
grant execute on function "permdock".permitted_organization_ids_by_permission(text, boolean) to authenticated;

create or replace function "permdock".permitted_customer_ids_by_permission(p_permission text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from "permdock".grant_keys(p_permission, 'customer') g(grant_key)
  cross join lateral "permdock".permitted_customer_ids(g.grant_key) a(id)
  except
  select d.id
  from "permdock".grant_keys(p_permission, 'customer', 'deny') g(grant_key)
  cross join lateral "permdock".permitted_customer_ids(g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_customer_ids_by_permission(text) from public, anon;
grant execute on function "permdock".permitted_customer_ids_by_permission(text) to authenticated;

-- with p_conditioned true, also the instances a conditioned allow reaches, minus only unconditional denies: the caller applies the row condition
create or replace function "permdock".permitted_customer_ids_by_permission(p_permission text, p_conditioned boolean)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer') g(grant_key)
    union all
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer', 'conditioned-allow') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_customer_ids(g.grant_key) a(id)
  except
  select d.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer', 'deny') g(grant_key)
    except
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer', 'conditioned-deny') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_customer_ids(g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_customer_ids_by_permission(text, boolean) from public, anon;
grant execute on function "permdock".permitted_customer_ids_by_permission(text, boolean) to authenticated;

-- the same for a user the caller names; no client role may execute them
create or replace function "permdock".permdock_has_permission_for(p_user uuid, p_permission text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from "permdock".grant_keys(p_permission, 'global') g(grant_key) where "permdock".permdock_has_for(p_user, g.grant_key))
    and not exists (select 1 from "permdock".grant_keys(p_permission, 'global', 'deny') g(grant_key) where "permdock".permdock_has_for(p_user, g.grant_key))
$$;
revoke execute on function "permdock".permdock_has_permission_for(uuid, text) from public, anon, authenticated;

create or replace function "permdock".permitted_organization_ids_by_permission_for(p_user uuid, p_permission text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from "permdock".grant_keys(p_permission, 'organization') g(grant_key)
  cross join lateral "permdock".permitted_organization_ids_for(p_user, g.grant_key) a(id)
  except
  select d.id
  from "permdock".grant_keys(p_permission, 'organization', 'deny') g(grant_key)
  cross join lateral "permdock".permitted_organization_ids_for(p_user, g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_organization_ids_by_permission_for(uuid, text) from public, anon, authenticated;

create or replace function "permdock".permitted_organization_ids_by_permission_for(p_user uuid, p_permission text, p_conditioned boolean)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization') g(grant_key)
    union all
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization', 'conditioned-allow') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_organization_ids_for(p_user, g.grant_key) a(id)
  except
  select d.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization', 'deny') g(grant_key)
    except
    select g.grant_key from "permdock".grant_keys(p_permission, 'organization', 'conditioned-deny') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_organization_ids_for(p_user, g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_organization_ids_by_permission_for(uuid, text, boolean) from public, anon, authenticated;

create or replace function "permdock".permitted_customer_ids_by_permission_for(p_user uuid, p_permission text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from "permdock".grant_keys(p_permission, 'customer') g(grant_key)
  cross join lateral "permdock".permitted_customer_ids_for(p_user, g.grant_key) a(id)
  except
  select d.id
  from "permdock".grant_keys(p_permission, 'customer', 'deny') g(grant_key)
  cross join lateral "permdock".permitted_customer_ids_for(p_user, g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_customer_ids_by_permission_for(uuid, text) from public, anon, authenticated;

create or replace function "permdock".permitted_customer_ids_by_permission_for(p_user uuid, p_permission text, p_conditioned boolean)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer') g(grant_key)
    union all
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer', 'conditioned-allow') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_customer_ids_for(p_user, g.grant_key) a(id)
  except
  select d.id
  from (
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer', 'deny') g(grant_key)
    except
    select g.grant_key from "permdock".grant_keys(p_permission, 'customer', 'conditioned-deny') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "permdock".permitted_customer_ids_for(p_user, g.grant_key) d(id)
$$;
revoke execute on function "permdock".permitted_customer_ids_by_permission_for(uuid, text, boolean) from public, anon, authenticated;

-- organization: holder counts (min / max) over the membership sources, checked at commit
create or replace function "permdock".permdock_holders_organization()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ids text[] := '{}';
  v_id text;
  v_key_0 "public"."memberships"."scope_id"%type;
  v_total bigint;
  v_count bigint;
begin
  if tg_relid = '"public"."memberships"'::regclass then
    if tg_op in ('UPDATE', 'DELETE') then
      v_ids := v_ids || case when old."scope"::text = 'organization' then old."scope_id"::text end;
    end if;
    if tg_op in ('INSERT', 'UPDATE') then
      v_ids := v_ids || case when new."scope"::text = 'organization' then new."scope_id"::text end;
    end if;
  end if;
  foreach v_id in array v_ids loop
    continue when v_id is null;
    v_key_0 := v_id;
    select count(*) into v_total
      from (
        select m."scope_id"::text as id, m."user_id"::text as user_id, m."role"::text as role, null::text as via, true as live
        from "public"."memberships" m
        where m."scope"::text = 'organization' and m."scope_id" = v_key_0
      ) h;
    select count(distinct h.user_id) into v_count
      from (
        select m."scope_id"::text as id, m."user_id"::text as user_id, m."role"::text as role, null::text as via, true as live
        from "public"."memberships" m
        where m."scope"::text = 'organization' and m."scope_id" = v_key_0
      ) h
      where h.live
        and h.role = 'owner';
    if v_total > 0 and v_count < 1 then
      raise exception using
        errcode = '23514',
        message = 'permdock: organization ' || v_id || ' keeps at least 1 owner',
        hint = 'last-holder';
    end if;
  end loop;
  return null;
end;
$$;
drop trigger if exists "permdock_holders_organization" on "public"."memberships";
create constraint trigger "permdock_holders_organization"
  after insert or update or delete on "public"."memberships"
  deferrable initially deferred
  for each row execute function "permdock".permdock_holders_organization();
