import { base, ignorePatterns } from '@permdock/ox-config/oxlint';
import { defineConfig } from 'oxlint';

export default defineConfig({
  extends: [base],
  ignorePatterns: [
    ...ignorePatterns,
    '.agents/**',
    '.cursor/**',
    '.claude/**',
    '**/.expo/**',
    'apps/marketing/components/ui/**',
    'apps/marketing/components/reui/**',
    'apps/marketing/components/blocks/**',
    'tests/integration/src/support/prisma/**',
    'apps/examples/prisma/src/generated/**',
    'tests/e2e/fixtures/*/build/**',
    '**/routeTree.gen.ts',
  ],
  options: {
    typeAware: true,
  },
  overrides: [
    {
      files: ['packages/**/*.{ts,tsx,mts,cts}'],
      rules: {
        'import/no-default-export': 'error',
        'oxc/no-async-await': 'off',
        // Same-package folders (core/conditions) import each other.
        'import/no-relative-parent-imports': 'off',
        // exactOptionalPropertyTypes + compact() use `undefined` as a sentinel.
        'eslint/no-undefined': 'off',
        'unicorn/no-useless-undefined': 'off',
        'oxc/no-optional-chaining': 'off',
        'oxc/no-rest-spread-properties': 'off',
        'eslint/no-use-before-define': 'off',
        'typescript/prefer-readonly-parameter-types': 'off',
        'unicorn/no-array-callback-reference': 'off',
        'eslint/max-lines-per-function': 'off',
        // Generic trees, frozen JSON, and isolatedDeclarations need assertions.
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/no-unnecessary-type-assertion': 'off',
        'typescript/no-unsafe-argument': 'off',
        'typescript/no-unnecessary-type-parameters': 'off',
        'typescript/no-unnecessary-boolean-literal-compare': 'off',
        'typescript/no-base-to-string': 'off',
        'typescript/promise-function-async': 'off',
        'typescript/no-non-null-assertion': 'off',
        'typescript/no-unsafe-return': 'off',
        'eslint/max-lines': 'off',
        'eslint/complexity': 'off',
        'import/max-dependencies': 'off',
        'eslint/no-void': 'off',
        'eslint/no-bitwise': 'off',
        'unicorn/prefer-math-trunc': 'off',
        'eslint/max-classes-per-file': 'off',
      },
    },
    {
      files: ['**/*.cjs'],
      rules: {
        'import/unambiguous': 'off',
        'import/no-commonjs': 'off',
        'typescript/no-require-imports': 'off',
        'typescript/no-var-requires': 'off',
        'typescript/no-unsafe-call': 'off',
        'typescript/no-unsafe-member-access': 'off',
      },
    },
    {
      files: [
        '**/*.config.ts',
        '**/*.config.mts',
        '**/vitest.config.ts',
        '**/tsdown.config.ts',
      ],
      rules: {
        'import/no-default-export': 'off',
      },
    },
    {
      files: [
        '**/*.{test,spec}.{ts,tsx}',
        '**/*.test-d.ts',
        '**/fixtures/**/*.ts',
        'packages/permdock/src/testing/**/*.ts',
        'tests/**/support/**/*.ts',
        'tests/e2e/src/**/*.ts',
        'tests/e2e/playwright.config.ts',
        'tests/runtimes/src/**/*.ts',
      ],
      rules: {
        'typescript/explicit-function-return-type': 'off',
        'typescript/explicit-module-boundary-types': 'off',
        'typescript/prefer-readonly-parameter-types': 'off',
        'vitest/require-test-timeout': 'off',
        'vitest/no-conditional-in-test': 'off',
        'vitest/no-conditional-expect': 'off',
        'eslint/max-lines-per-function': 'off',
        'eslint/require-unicode-regexp': 'off',
        'eslint/no-unused-vars': 'off',
        'import/no-relative-parent-imports': 'off',
        'typescript/no-unsafe-argument': 'off',
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/no-unsafe-member-access': 'off',
        'typescript/no-unsafe-call': 'off',
        'typescript/no-unsafe-assignment': 'off',
        'typescript/no-unnecessary-type-assertion': 'off',
        'typescript/require-await': 'off',
        'typescript/promise-function-async': 'off',
        'typescript/no-floating-promises': 'off',
        'typescript/no-confusing-void-expression': 'off',
        'eslint/max-lines': 'off',
        'import/max-dependencies': 'off',
        'eslint/require-await': 'off',
        'unicorn/prefer-type-error': 'off',
        'eslint/no-void': 'off',
        'typescript/no-non-null-assertion': 'off',
        'vitest/no-conditional-tests': 'off',
        'vitest/valid-title': 'off',
        'vitest/expect-expect': 'off',
        'eslint/no-await-in-loop': 'off',
        'typescript/no-unnecessary-template-expression': 'off',
        // Case-local helpers stay next to the assertions that use them.
        'unicorn/consistent-function-scoping': 'off',
      },
    },
    {
      files: ['tests/**/*.{ts,tsx}', 'scripts/**/*.ts'],
      rules: {
        'oxc/no-async-await': 'off',
        'oxc/no-optional-chaining': 'off',
        'oxc/no-rest-spread-properties': 'off',
        'eslint/no-undefined': 'off',
        'unicorn/import-style': 'off',
        'unicorn/prefer-import-meta-properties': 'off',
        'typescript/no-unsafe-assignment': 'off',
        'typescript/no-unsafe-call': 'off',
        'typescript/no-unsafe-member-access': 'off',
        'typescript/no-unsafe-return': 'off',
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/explicit-function-return-type': 'off',
        'typescript/explicit-module-boundary-types': 'off',
        'import/no-relative-parent-imports': 'off',
        'node/no-process-env': 'off',
        'import/no-default-export': 'off',
        'unicorn/no-array-callback-reference': 'off',
        // Child-process scripts under tests run as ESM, never through require(esm).
        'node/no-top-level-await': 'off',
      },
    },
    {
      files: ['packages/cli/**/*.{ts,tsx}'],
      rules: {
        'import/no-default-export': 'off',
        'eslint/max-lines': 'off',
        'eslint/max-lines-per-function': 'off',
        'eslint/complexity': 'off',
        'import/max-dependencies': 'off',
        'eslint/no-await-in-loop': 'off',
        'eslint/require-unicode-regexp': 'off',
        'eslint/no-negated-condition': 'off',
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/no-unsafe-assignment': 'off',
        'typescript/no-unsafe-member-access': 'off',
        'typescript/no-unsafe-call': 'off',
        'typescript/no-unsafe-argument': 'off',
        'typescript/no-unsafe-return': 'off',
        'typescript/strict-boolean-expressions': 'off',
        'typescript/no-unnecessary-template-expression': 'off',
        'typescript/prefer-includes': 'off',
        'typescript/explicit-function-return-type': 'off',
        'typescript/explicit-module-boundary-types': 'off',
        'unicorn/prefer-module': 'off',
        'unicorn/import-style': 'off',
        'unicorn/prefer-import-meta-properties': 'off',
        'unicorn/prefer-single-call': 'off',
        'unicorn/no-immediate-mutation': 'off',
        'unicorn/prefer-code-point': 'off',
        'unicorn/prefer-string-replace-all': 'off',
        'unicorn/no-negated-condition': 'off',
        'node/no-top-level-await': 'off',
        'node/no-process-env': 'off',
        'eslint/no-undefined': 'off',
        'unicorn/no-useless-undefined': 'off',
      },
    },
    {
      files: [
        'packages/permdock/src/terminal/**/*.{ts,tsx}',
        'apps/examples/terminal/**/*.{ts,tsx}',
      ],
      rules: {
        'node/no-process-env': 'off',
        'unicorn/no-process-exit': 'off',
        'eslint/no-await-in-loop': 'off',
        'eslint/max-depth': 'off',
        'unicorn/prefer-top-level-await': 'off',
        'eslint/require-await': 'off',
        'typescript/require-await': 'off',
        'typescript/no-unsafe-assignment': 'off',
        'typescript/no-unsafe-call': 'off',
        'typescript/no-unsafe-member-access': 'off',
        'typescript/no-unsafe-argument': 'off',
      },
    },
    {
      files: [
        'packages/permdock/src/nest/**/*.{ts,tsx}',
        'apps/examples/nest/**/*.{ts,tsx}',
        'tests/integration/src/http/nest.test.ts',
      ],
      rules: {
        // Nest modules, controllers and side-effect `reflect-metadata`.
        'eslint/class-methods-use-this': 'off',
        'typescript/no-extraneous-class': 'off',
        'eslint/max-classes-per-file': 'off',
        'import/no-unassigned-import': 'off',
        'typescript/explicit-member-accessibility': 'off',
      },
    },
    {
      files: ['apps/examples/**/*.{ts,tsx}'],
      rules: {
        // App-router and factory files import across src/ folders.
        'import/no-relative-parent-imports': 'off',
        // Vite / Next client entries boot with top-level await.
        'node/no-top-level-await': 'off',
        // Adapter factories take Policy (TUser = unknown); typed policies need a cast.
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/no-unsafe-return': 'off',
        // Example servers read PORT from the environment.
        'node/no-process-env': 'off',
      },
    },
    {
      files: ['apps/marketing/**/*.{ts,tsx}'],
      rules: {
        'node/no-process-env': 'off',
        'import/no-default-export': 'off',
        'eslint/max-lines': 'off',
        'eslint/max-lines-per-function': 'off',
        'import/max-dependencies': 'off',
        'oxc/no-async-await': 'off',
        'eslint/no-undefined': 'off',
        'unicorn/import-style': 'off',
        'unicorn/prefer-import-meta-properties': 'off',
        'typescript/no-unsafe-type-assertion': 'off',
        'typescript/no-confusing-void-expression': 'off',
        'typescript/strict-boolean-expressions': 'off',
        'typescript/no-misused-promises': 'off',
        'typescript/strict-void-return': 'off',
        'typescript/consistent-return': 'off',
        'typescript/no-deprecated': 'off',
      },
    },
    {
      files: ['tests/e2e/fixtures/**/*.{ts,tsx,svelte,vue}'],
      rules: {
        // Framework file conventions (routes, loaders, SFCs), as for apps/** below.
        'typescript/prefer-readonly-parameter-types': 'off',
        'typescript/promise-function-async': 'off',
        'typescript/explicit-function-return-type': 'off',
        'unicorn/no-array-callback-reference': 'off',
        'oxc/no-async-await': 'off',
        'oxc/no-optional-chaining': 'off',
        'oxc/no-map-spread': 'off',
        'eslint/no-undefined': 'off',
        'unicorn/no-useless-undefined': 'off',
        'eslint/no-use-before-define': 'off',
        'eslint/no-void': 'off',
        'import/unambiguous': 'off',
        'node/no-top-level-await': 'off',
        'import/no-relative-parent-imports': 'off',
      },
    },
    {
      files: ['apps/**/*.{ts,tsx,mts,cts}'],
      rules: {
        // Next.js Server Components, route handlers and `next.config` redirects.
        'oxc/no-async-await': 'off',
        // MDX component maps and Fumadocs layout props.
        'oxc/no-rest-spread-properties': 'off',
        'oxc/no-optional-chaining': 'off',
        // Framework file conventions: pages, layouts, CSS entry, generated props.
        'typescript/explicit-function-return-type': 'off',
        'import/no-default-export': 'off',
        'typescript/explicit-module-boundary-types': 'off',
        'typescript/prefer-readonly-parameter-types': 'off',
        'import/no-unassigned-import': 'off',
        'unicorn/no-array-callback-reference': 'off',
      },
    },
  ],
});
