-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- rbac scaffold (Supabase Custom Claims and RBAC)
-- authorize: database (reads user_roles on every call)
-- enable the hook in supabase/config.toml:
--   [auth.hook.custom_access_token]
--   enabled = true
--   uri = "pg-functions://postgres/public/custom_access_token_hook"
do $$ begin
  create type "public"."app_role" as enum ('admin', 'member');
exception when duplicate_object then null;
end $$;
do $$ begin
  create type "public"."app_permission" as enum ('post.read', 'post.update', 'post.delete', 'post.publish', 'post.archive', 'post.create', 'post.list');
exception when duplicate_object then null;
end $$;

create table if not exists "public"."user_roles" (
  user_id uuid not null references auth.users on delete cascade,
  role "public"."app_role" not null,
  primary key (user_id, role)
);

create table if not exists "public"."role_permissions" (
  role "public"."app_role" not null,
  permission "public"."app_permission" not null,
  primary key (role, permission)
);

alter table "public"."user_roles" enable row level security;
alter table "public"."role_permissions" enable row level security;

insert into "public"."role_permissions" (role, permission) values ('admin', 'post.read') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('admin', 'post.update') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('admin', 'post.delete') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('admin', 'post.publish') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('admin', 'post.archive') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('admin', 'post.create') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('admin', 'post.list') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('member', 'post.read') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('member', 'post.list') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('member', 'post.create') on conflict do nothing;
insert into "public"."role_permissions" (role, permission) values ('member', 'post.update') on conflict do nothing;

create or replace function "public"."authorize"(
  requested_permission "public"."app_permission",
  requested_tenant text default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
begin
  if uid is null then
    return false;
  end if;
  if requested_tenant is not null then
    return exists (
      select 1
      from "public"."organization_members" m
      join "public"."role_permissions" rp on rp.role::text = m."role"::text
      where m."user_id"::text = uid::text
        and m."organization_id"::text = requested_tenant
        and rp.permission = requested_permission
    );
  end if;
  return exists (
    select 1
    from "public"."user_roles" ur
    join "public"."role_permissions" rp on rp.role = ur.role
    where ur.user_id = uid
      and rp.permission = requested_permission
  );
end;
$$;

revoke execute on function "public"."authorize"("public"."app_permission", text) from public, anon;
grant execute on function "public"."authorize"("public"."app_permission", text) to authenticated;

create or replace function "public"."custom_access_token_hook"(event jsonb)
returns jsonb
language plpgsql
stable
set search_path = ''
as $$
declare
  claims jsonb := event -> 'claims';
  held jsonb;
begin
  select case count(*) when 0 then null when 1 then to_jsonb(min(ur.role::text)) else jsonb_agg(ur.role::text order by ur.role::text) end
    into held
    from "public"."user_roles" ur
    where ur.user_id = (event ->> 'user_id')::uuid;
  if held is not null then
    claims := jsonb_set(claims, '{user_role}', held);
  end if;
  return jsonb_set(event, '{claims}', claims);
end;
$$;

grant usage on schema "public" to supabase_auth_admin;
grant execute on function "public"."custom_access_token_hook"(jsonb) to supabase_auth_admin;
revoke execute on function "public"."custom_access_token_hook"(jsonb) from authenticated, anon, public;
grant select on table "public"."user_roles" to supabase_auth_admin;
revoke all on table "public"."user_roles" from authenticated, anon, public;
revoke all on table "public"."role_permissions" from authenticated, anon, public;
drop policy if exists "Allow auth admin to read user roles" on "public"."user_roles";
create policy "Allow auth admin to read user roles" on "public"."user_roles"
  as permissive for select
  to supabase_auth_admin
  using (true);

revoke all on table "post" from anon, authenticated;
grant select, insert, update, delete on table "post" to authenticated;
alter table "post" enable row level security;

drop policy if exists "admin_post_read" on "post";
create policy "admin_post_read"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select "public".authorize('post.read')));

drop policy if exists "admin_post_update" on "post";
create policy "admin_post_update"
  on "post"
  as permissive
  for update
  to authenticated
  using ((select "public".authorize('post.update')))
  with check ((select "public".authorize('post.update')));

drop policy if exists "admin_post_delete" on "post";
create policy "admin_post_delete"
  on "post"
  as permissive
  for delete
  to authenticated
  using ((select "public".authorize('post.delete')));

drop policy if exists "admin_post_create" on "post";
create policy "admin_post_create"
  on "post"
  as permissive
  for insert
  to authenticated
  with check ((select "public".authorize('post.create')));

drop policy if exists "admin_post_list" on "post";
create policy "admin_post_list"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select "public".authorize('post.list')));

drop policy if exists "member_post_read" on "post";
create policy "member_post_read"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select "public".authorize('post.read', "orgId"::text)) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}'))));

drop policy if exists "member_post_list" on "post";
create policy "member_post_list"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select "public".authorize('post.list', "orgId"::text)) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}'))));

drop policy if exists "member_post_create" on "post";
create policy "member_post_create"
  on "post"
  as permissive
  for insert
  to authenticated
  with check ((select "public".authorize('post.create', "orgId"::text)) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}'))));

drop policy if exists "member_post_update" on "post";
create policy "member_post_update"
  on "post"
  as permissive
  for update
  to authenticated
  using ((select "public".authorize('post.update', "orgId"::text)) and ((exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}')) and "authorId" = (select auth.uid()))))
  with check ((select "public".authorize('post.update', "orgId"::text)) and ("authorId" = (select auth.uid())));
