-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- rbac scaffold (Supabase Custom Claims and RBAC)
-- authorize: jwt (reads the hook claims; stale until the token refreshes)
-- enable the hook in supabase/config.toml:
--   [auth.hook.custom_access_token]
--   enabled = true
--   uri = "pg-functions://postgres/app/custom_access_token_hook"
create schema if not exists "app";
do $$ begin
  create type "app"."app_role" as enum ('admin', 'member');
exception when duplicate_object then null;
end $$;
do $$ begin
  create type "app"."app_permission" as enum ('post.read', 'post.update', 'post.delete', 'post.publish', 'post.archive', 'post.create', 'post.list');
exception when duplicate_object then null;
end $$;

create table if not exists "app"."user_roles" (
  user_id uuid not null references auth.users on delete cascade,
  role "app"."app_role" not null,
  primary key (user_id, role)
);

alter table "app"."user_roles" enable row level security;

-- permdock helpers (jwt: reads the role and memberships claims)
-- policies call them uncorrelated, so Postgres evaluates each once per statement

create schema if not exists "app";
grant usage on schema "app" to authenticated;

create table if not exists "app".role_permissions (
  role text not null,
  permission text not null,
  grant_key text not null,
  scope text not null check (scope in ('global', 'tenant', 'team')),
  effect text not null default 'allow' check (effect in ('allow', 'deny')),
  primary key (role, grant_key, scope)
);
alter table "app".role_permissions enable row level security;
revoke all on table "app".role_permissions from anon, authenticated, public;

insert into "app".role_permissions (role, permission, grant_key, scope, effect) values
  ('admin', 'post.read', 'post.read', 'global', 'allow'),
  ('admin', 'post.update', 'post.update#1', 'global', 'allow'),
  ('admin', 'post.delete', 'post.delete', 'global', 'allow'),
  ('admin', 'post.create', 'post.create', 'global', 'allow'),
  ('admin', 'post.list', 'post.list', 'global', 'allow'),
  ('member', 'post.read', 'post.read', 'tenant', 'allow'),
  ('member', 'post.list', 'post.list', 'tenant', 'allow'),
  ('member', 'post.create', 'post.create', 'tenant', 'allow'),
  ('member', 'post.update', 'post.update#2', 'tenant', 'allow')
on conflict (role, grant_key, scope) do update
  set permission = excluded.permission, effect = excluded.effect;
delete from "app".role_permissions
where (role, grant_key, scope) not in (values
  ('admin', 'post.read', 'global'),
  ('admin', 'post.update#1', 'global'),
  ('admin', 'post.delete', 'global'),
  ('admin', 'post.create', 'global'),
  ('admin', 'post.list', 'global'),
  ('member', 'post.read', 'tenant'),
  ('member', 'post.list', 'tenant'),
  ('member', 'post.create', 'tenant'),
  ('member', 'post.update#2', 'tenant')
);

create or replace function "app".permdock_has(p_grant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select auth.uid())::text, '') <> '' and exists (
    select 1
    from jsonb_array_elements_text(
      case jsonb_typeof(coalesce(nullif(((select auth.jwt()) -> 'user_role'), 'null'::jsonb), (select auth.jwt()) -> 'app_metadata' -> 'user_role'))
        when 'array' then coalesce(nullif(((select auth.jwt()) -> 'user_role'), 'null'::jsonb), (select auth.jwt()) -> 'app_metadata' -> 'user_role')
        when 'string' then jsonb_build_array(coalesce(nullif(((select auth.jwt()) -> 'user_role'), 'null'::jsonb), (select auth.jwt()) -> 'app_metadata' -> 'user_role'))
        else '[]'::jsonb
      end
    ) r(role)
    join "app".role_permissions rp on rp.role = r.role
    where rp.grant_key = p_grant
      and rp.scope = 'global'
  )
$$;
revoke execute on function "app".permdock_has(text) from public, anon;
grant execute on function "app".permdock_has(text) to authenticated;

create or replace function "app".permitted_tenant_ids(p_grant text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select (m ->> 'tenant')::uuid
  from jsonb_array_elements(
      case jsonb_typeof(coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships')) when 'array' then coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships') else '[]'::jsonb end
    ) m
    cross join lateral jsonb_array_elements_text(
      case jsonb_typeof(m -> 'roles') when 'array' then m -> 'roles' else '[]'::jsonb end
    ) r(role)
  join "app".role_permissions rp on rp.role = r.role
  where coalesce((select auth.uid())::text, '') <> ''
    and rp.grant_key = p_grant
    and rp.scope = 'tenant'
    and m ->> 'tenant' is not null
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or m ->> 'tenant' = nullif(((select auth.jwt()) ->> 'tenant_id'), ''))
    and case jsonb_typeof(m -> 'expiresAt')
      when 'number' then (m ->> 'expiresAt')::numeric > extract(epoch from now())
      else true
    end
$$;
revoke execute on function "app".permitted_tenant_ids(text) from public, anon;
grant execute on function "app".permitted_tenant_ids(text) to authenticated;

create or replace function "app".permitted_team_ids(p_grant text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select (m ->> 'team')::uuid
  from jsonb_array_elements(
      case jsonb_typeof(coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships')) when 'array' then coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships') else '[]'::jsonb end
    ) m
    cross join lateral jsonb_array_elements_text(
      case jsonb_typeof(m -> 'roles') when 'array' then m -> 'roles' else '[]'::jsonb end
    ) r(role)
  join "app".role_permissions rp on rp.role = r.role
  where coalesce((select auth.uid())::text, '') <> ''
    and rp.grant_key = p_grant
    and rp.scope = 'team'
    and m ->> 'team' is not null
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or m ->> 'tenant' = nullif(((select auth.jwt()) ->> 'tenant_id'), ''))
    and case jsonb_typeof(m -> 'expiresAt')
      when 'number' then (m ->> 'expiresAt')::numeric > extract(epoch from now())
      else true
    end
$$;
revoke execute on function "app".permitted_team_ids(text) from public, anon;
grant execute on function "app".permitted_team_ids(text) to authenticated;

create or replace function "app"."authorize"(
  requested_permission "app"."app_permission",
  requested_tenant text default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  claims jsonb := (select auth.jwt());
  role_claim jsonb;
begin
  if claims is null or (select auth.uid()) is null then
    return false;
  end if;
  if requested_tenant is not null then
    return exists (
      select 1
      from jsonb_array_elements(
        case jsonb_typeof(coalesce(claims -> 'memberships', claims -> 'app_metadata' -> 'memberships'))
          when 'array' then coalesce(claims -> 'memberships', claims -> 'app_metadata' -> 'memberships')
          else '[]'::jsonb
        end
      ) m
      cross join lateral jsonb_array_elements_text(
        case jsonb_typeof(m -> 'roles') when 'array' then m -> 'roles' else '[]'::jsonb end
      ) r(role)
      join "app"."role_permissions" rp on rp.role = r.role
      where m ->> 'tenant' = requested_tenant
        and rp.permission = requested_permission::text
        and rp.scope = 'tenant'
        and rp.effect = 'allow'
    );
  end if;
  -- a top-level null (no role row) falls back to app_metadata, like subjectFromSupabase
  role_claim := coalesce(nullif(claims -> 'user_role', 'null'::jsonb), claims -> 'app_metadata' -> 'user_role');
  return exists (
    select 1
    from jsonb_array_elements_text(
      case jsonb_typeof(role_claim)
        when 'array' then role_claim
        when 'string' then jsonb_build_array(role_claim)
        else '[]'::jsonb
      end
    ) r(role)
    join "app"."role_permissions" rp on rp.role = r.role
    where rp.permission = requested_permission::text
      and rp.scope = 'global'
      and rp.effect = 'allow'
  );
end;
$$;

revoke execute on function "app"."authorize"("app"."app_permission", text) from public, anon;
grant execute on function "app"."authorize"("app"."app_permission", text) to authenticated;

create or replace function "app"."custom_access_token_hook"(event jsonb)
returns jsonb
language plpgsql
stable
set search_path = ''
as $$
declare
  claims jsonb := event -> 'claims';
  held jsonb;
begin
  select case count(*) when 0 then null when 1 then to_jsonb(min(ur.role::text)) else jsonb_agg(ur.role::text order by ur.role::text) end
    into held
    from "app"."user_roles" ur
    where ur.user_id = (event ->> 'user_id')::uuid;
  if held is not null then
    claims := jsonb_set(claims, '{user_role}', held);
  end if;
  return jsonb_set(event, '{claims}', claims);
end;
$$;

grant usage on schema "app" to supabase_auth_admin;
grant execute on function "app"."custom_access_token_hook"(jsonb) to supabase_auth_admin;
revoke execute on function "app"."custom_access_token_hook"(jsonb) from authenticated, anon, public;
grant select on table "app"."user_roles" to supabase_auth_admin;
revoke all on table "app"."user_roles" from authenticated, anon, public;
drop policy if exists "Allow auth admin to read user roles" on "app"."user_roles";
create policy "Allow auth admin to read user roles" on "app"."user_roles"
  as permissive for select
  to supabase_auth_admin
  using (true);

revoke all on table "post" from anon, authenticated;
grant select, insert, update, delete on table "post" to authenticated;
alter table "post" enable row level security;

drop policy if exists "post_select" on "post";
create policy "post_select"
  on "post"
  as permissive
  for select
  to authenticated
  using (((select "app".permdock_has('post.read')) or ("orgId" in (select "app".permitted_tenant_ids('post.read')))) or ((select "app".permdock_has('post.list')) or ("orgId" in (select "app".permitted_tenant_ids('post.list')))));

drop policy if exists "post_update" on "post";
create policy "post_update"
  on "post"
  as permissive
  for update
  to authenticated
  using ((select "app".permdock_has('post.update#1')) or (("orgId" in (select "app".permitted_tenant_ids('post.update#2'))) and ("authorId" = (select auth.uid()))))
  with check ((select "app".permdock_has('post.update#1')) or (("orgId" in (select "app".permitted_tenant_ids('post.update#2'))) and ("authorId" = (select auth.uid()))));

drop policy if exists "post_delete" on "post";
create policy "post_delete"
  on "post"
  as permissive
  for delete
  to authenticated
  using ((select "app".permdock_has('post.delete')));

drop policy if exists "post_insert" on "post";
create policy "post_insert"
  on "post"
  as permissive
  for insert
  to authenticated
  with check ((select "app".permdock_has('post.create')) or ("orgId" in (select "app".permitted_tenant_ids('post.create'))));
