-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- rbac scaffold (Supabase Custom Claims and RBAC)
-- authorize: jwt (reads the hook claims; stale until the token refreshes)
-- the custom access token hook that writes user_role and memberships: permdock supabase hook generate
create schema if not exists "app";
do $$ begin
  create type "app"."app_role" as enum ('admin', 'member');
exception when duplicate_object then null;
end $$;
do $$ begin
  create type "app"."app_permission" as enum ('post.read', 'post.update', 'post.delete', 'post.publish', 'post.archive', 'post.create', 'post.list');
exception when duplicate_object then null;
end $$;

create table if not exists "app"."user_roles" (
  user_id uuid not null references auth.users on delete cascade,
  role "app"."app_role" not null,
  primary key (user_id, role)
);

alter table "app"."user_roles" enable row level security;
revoke all on table "app"."user_roles" from authenticated, anon, public;

-- permdock helpers (jwt: reads the role and memberships claims)
-- policies call them uncorrelated, so Postgres evaluates each once per statement

create schema if not exists "app";
revoke all on schema "app" from public;
grant usage on schema "app" to authenticated;

-- the caller's user id: the sub of request.jwt.claims, or null when it is empty or absent
create or replace function "app".permdock_user_id()
returns uuid
language sql
stable
set search_path = ''
as $$
  select nullif(
    nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub',
    ''
  )::uuid
$$;
revoke execute on function "app".permdock_user_id() from public, anon;
grant execute on function "app".permdock_user_id() to authenticated;

create table if not exists "app".role_permissions (
  role text not null,
  permission text not null,
  grant_key text not null,
  scope text not null check (scope ~ '^[a-z][a-z0-9_]*$'),
  effect text not null default 'allow' check (effect in ('allow', 'deny')),
  primary key (role, grant_key, scope)
);
alter table "app".role_permissions enable row level security;
revoke all on table "app".role_permissions from anon, authenticated, public;

insert into "app".role_permissions (role, permission, grant_key, scope, effect) values
  ('admin', 'post.read', 'post.read', 'global', 'allow'),
  ('admin', 'post.update', 'post.update#1', 'global', 'allow'),
  ('admin', 'post.delete', 'post.delete', 'global', 'allow'),
  ('admin', 'post.publish', 'post.publish', 'global', 'allow'),
  ('admin', 'post.archive', 'post.archive', 'global', 'allow'),
  ('admin', 'post.create', 'post.create', 'global', 'allow'),
  ('admin', 'post.list', 'post.list', 'global', 'allow'),
  ('member', 'post.read', 'post.read', 'tenant', 'allow'),
  ('member', 'post.list', 'post.list', 'tenant', 'allow'),
  ('member', 'post.create', 'post.create', 'tenant', 'allow'),
  ('member', 'post.update', 'post.update#2', 'tenant', 'allow')
on conflict (role, grant_key, scope) do update
  set permission = excluded.permission, effect = excluded.effect;
delete from "app".role_permissions
where (role, grant_key, scope) not in (values
  ('admin', 'post.read', 'global'),
  ('admin', 'post.update#1', 'global'),
  ('admin', 'post.delete', 'global'),
  ('admin', 'post.publish', 'global'),
  ('admin', 'post.archive', 'global'),
  ('admin', 'post.create', 'global'),
  ('admin', 'post.list', 'global'),
  ('member', 'post.read', 'tenant'),
  ('member', 'post.list', 'tenant'),
  ('member', 'post.create', 'tenant'),
  ('member', 'post.update#2', 'tenant')
);

create or replace function "app".permdock_has(p_grant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select "app".permdock_user_id())::text, '') <> '' and exists (
    select 1
    from jsonb_array_elements_text(
      case jsonb_typeof(coalesce(nullif(((select auth.jwt()) -> 'user_role'), 'null'::jsonb), (select auth.jwt()) -> 'app_metadata' -> 'user_role'))
        when 'array' then coalesce(nullif(((select auth.jwt()) -> 'user_role'), 'null'::jsonb), (select auth.jwt()) -> 'app_metadata' -> 'user_role')
        when 'string' then jsonb_build_array(coalesce(nullif(((select auth.jwt()) -> 'user_role'), 'null'::jsonb), (select auth.jwt()) -> 'app_metadata' -> 'user_role'))
        else '[]'::jsonb
      end
    ) r(role)
    join "app".role_permissions rp on rp.role = r.role
    where rp.grant_key = p_grant
      and rp.scope = 'global'
  )
$$;
revoke execute on function "app".permdock_has(text) from public, anon;
grant execute on function "app".permdock_has(text) to authenticated;

create or replace function "app".permitted_tenant_ids(p_grant text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select (m ->> 'id')::uuid
  from jsonb_array_elements(
      case jsonb_typeof(coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships')) when 'array' then coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships') else '[]'::jsonb end
    ) m
    cross join lateral jsonb_array_elements_text(
      case jsonb_typeof(m -> 'roles') when 'array' then m -> 'roles' else '[]'::jsonb end
    ) r(role)
  join "app".role_permissions rp on rp.role = r.role
  where coalesce((select "app".permdock_user_id())::text, '') <> ''
    and rp.grant_key = p_grant
    and rp.scope = 'tenant'
    and m ->> 'scope' = 'tenant'
    and m ->> 'id' is not null
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or m ->> 'id' = nullif(((select auth.jwt()) ->> 'tenant_id'), ''))
    and case jsonb_typeof(m -> 'expiresAt')
      when 'number' then (m ->> 'expiresAt')::numeric > extract(epoch from now())
      else true
    end
$$;
revoke execute on function "app".permitted_tenant_ids(text) from public, anon;
grant execute on function "app".permitted_tenant_ids(text) to authenticated;

create or replace function "app".member_tenant_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select distinct (m ->> 'id')::uuid
  from jsonb_array_elements(
    case jsonb_typeof(coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships')) when 'array' then coalesce(((select auth.jwt()) -> 'memberships'), (select auth.jwt()) -> 'app_metadata' -> 'memberships') else '[]'::jsonb end
  ) m
  where coalesce((select "app".permdock_user_id())::text, '') <> ''
    and m ->> 'scope' = 'tenant'
    and m ->> 'id' is not null
    and jsonb_typeof(m -> 'roles') = 'array'
    and jsonb_array_length(m -> 'roles') > 0
    and case jsonb_typeof(m -> 'expiresAt')
      when 'number' then (m ->> 'expiresAt')::numeric > extract(epoch from now())
      else true
    end
$$;
revoke execute on function "app".member_tenant_ids() from public, anon;
grant execute on function "app".member_tenant_ids() to authenticated;

create or replace function "app".member_tenant_ids_for(p_user uuid)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select distinct m."organization_id"::uuid
  from "public"."organization_members" m
  where m."user_id" = p_user
    and m."role" is not null
$$;
revoke execute on function "app".member_tenant_ids_for(uuid) from public, anon, authenticated;

-- the grant keys a permission key reaches on one scope: its unconditional allows, with p_effect 'deny' every deny, and with 'conditioned-allow' or 'conditioned-deny' the allows or denies that carry a row condition
create or replace function "app".grant_keys(p_permission text, p_scope text, p_effect text default 'allow')
returns setof text
language sql
stable
set search_path = ''
as $$
  select g.grant_key
  from pg_catalog.jsonb_array_elements_text(coalesce(
    '{"global":{"post.archive":{"allow":["post.archive"],"deny":[]},"post.create":{"allow":["post.create"],"deny":[]},"post.delete":{"allow":["post.delete"],"deny":[]},"post.list":{"allow":["post.list"],"deny":[]},"post.publish":{"allow":["post.publish"],"deny":[]},"post.read":{"allow":["post.read"],"deny":[]},"post.update":{"allow":["post.update#1"],"deny":[]}},"tenant":{"post.create":{"allow":["post.create"],"deny":[]},"post.list":{"allow":["post.list"],"deny":[]},"post.read":{"allow":["post.read"],"deny":[]},"post.update":{"allow":[],"deny":[],"conditioned-allow":["post.update#2"]}}}'::jsonb -> p_scope -> p_permission -> p_effect,
    '[]'::jsonb
  )) g(grant_key)
$$;
revoke execute on function "app".grant_keys(text, text, text) from public, anon;
grant execute on function "app".grant_keys(text, text, text) to authenticated;

-- the helpers by permission key: unconditional allows minus any deny
create or replace function "app".permdock_has_permission(p_permission text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from "app".grant_keys(p_permission, 'global') g(grant_key) where "app".permdock_has(g.grant_key))
    and not exists (select 1 from "app".grant_keys(p_permission, 'global', 'deny') g(grant_key) where "app".permdock_has(g.grant_key))
$$;
revoke execute on function "app".permdock_has_permission(text) from public, anon;
grant execute on function "app".permdock_has_permission(text) to authenticated;

create or replace function "app".permitted_tenant_ids_by_permission(p_permission text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from "app".grant_keys(p_permission, 'tenant') g(grant_key)
  cross join lateral "app".permitted_tenant_ids(g.grant_key) a(id)
  except
  select d.id
  from "app".grant_keys(p_permission, 'tenant', 'deny') g(grant_key)
  cross join lateral "app".permitted_tenant_ids(g.grant_key) d(id)
$$;
revoke execute on function "app".permitted_tenant_ids_by_permission(text) from public, anon;
grant execute on function "app".permitted_tenant_ids_by_permission(text) to authenticated;

-- with p_conditioned true, also the instances a conditioned allow reaches, minus only unconditional denies: the caller applies the row condition
create or replace function "app".permitted_tenant_ids_by_permission(p_permission text, p_conditioned boolean)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select a.id
  from (
    select g.grant_key from "app".grant_keys(p_permission, 'tenant') g(grant_key)
    union all
    select g.grant_key from "app".grant_keys(p_permission, 'tenant', 'conditioned-allow') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "app".permitted_tenant_ids(g.grant_key) a(id)
  except
  select d.id
  from (
    select g.grant_key from "app".grant_keys(p_permission, 'tenant', 'deny') g(grant_key)
    except
    select g.grant_key from "app".grant_keys(p_permission, 'tenant', 'conditioned-deny') g(grant_key)
    where p_conditioned
  ) g
  cross join lateral "app".permitted_tenant_ids(g.grant_key) d(id)
$$;
revoke execute on function "app".permitted_tenant_ids_by_permission(text, boolean) from public, anon;
grant execute on function "app".permitted_tenant_ids_by_permission(text, boolean) to authenticated;

create or replace function "app"."authorize"(
  requested_permission "app"."app_permission",
  requested_tenant text default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  claims jsonb := (select auth.jwt());
  role_claim jsonb;
begin
  if claims is null or (select auth.uid()) is null then
    return false;
  end if;
  -- a top-level null (no role row) falls back to app_metadata, like subjectFromSupabase
  role_claim := coalesce(nullif(claims -> 'user_role', 'null'::jsonb), claims -> 'app_metadata' -> 'user_role');
  if requested_tenant is not null then
    return (exists (
      select 1
      from jsonb_array_elements(
        case jsonb_typeof(coalesce(claims -> 'memberships', claims -> 'app_metadata' -> 'memberships'))
          when 'array' then coalesce(claims -> 'memberships', claims -> 'app_metadata' -> 'memberships')
          else '[]'::jsonb
        end
      ) m
      cross join lateral jsonb_array_elements_text(
        case jsonb_typeof(m -> 'roles') when 'array' then m -> 'roles' else '[]'::jsonb end
      ) r(role)
      join "app"."role_permissions" rp on rp.role = r.role
      where m ->> 'scope' = 'tenant'
        and m ->> 'id' = requested_tenant
        and case jsonb_typeof(m -> 'expiresAt')
          when 'number' then (m ->> 'expiresAt')::numeric > extract(epoch from now())
          else true
        end
        and rp.permission = requested_permission::text
        and rp.scope = 'tenant'
        and rp.effect = 'allow'
        and rp.grant_key = rp.permission
    ))
    and not exists (
      select 1
      from jsonb_array_elements(
        case jsonb_typeof(coalesce(claims -> 'memberships', claims -> 'app_metadata' -> 'memberships'))
          when 'array' then coalesce(claims -> 'memberships', claims -> 'app_metadata' -> 'memberships')
          else '[]'::jsonb
        end
      ) m
      cross join lateral jsonb_array_elements_text(
        case jsonb_typeof(m -> 'roles') when 'array' then m -> 'roles' else '[]'::jsonb end
      ) r(role)
      join "app"."role_permissions" rp on rp.role = r.role
      where m ->> 'scope' = 'tenant'
        and m ->> 'id' = requested_tenant
        and case jsonb_typeof(m -> 'expiresAt')
          when 'number' then (m ->> 'expiresAt')::numeric > extract(epoch from now())
          else true
        end
        and rp.permission = requested_permission::text
        and rp.scope = 'tenant'
        and rp.effect = 'deny'
    )
    and not exists (
      select 1
      from jsonb_array_elements_text(
        case jsonb_typeof(role_claim)
          when 'array' then role_claim
          when 'string' then jsonb_build_array(role_claim)
          else '[]'::jsonb
        end
      ) r(role)
      join "app"."role_permissions" rp on rp.role = r.role
      where rp.permission = requested_permission::text
        and rp.scope = 'global'
        and rp.effect = 'deny'
    );
  end if;
  return exists (
      select 1
      from jsonb_array_elements_text(
        case jsonb_typeof(role_claim)
          when 'array' then role_claim
          when 'string' then jsonb_build_array(role_claim)
          else '[]'::jsonb
        end
      ) r(role)
      join "app"."role_permissions" rp on rp.role = r.role
      where rp.permission = requested_permission::text
        and rp.scope = 'global'
        and rp.effect = 'allow'
        and rp.grant_key = rp.permission
    )
    and not exists (
      select 1
      from jsonb_array_elements_text(
        case jsonb_typeof(role_claim)
          when 'array' then role_claim
          when 'string' then jsonb_build_array(role_claim)
          else '[]'::jsonb
        end
      ) r(role)
      join "app"."role_permissions" rp on rp.role = r.role
      where rp.permission = requested_permission::text
        and rp.scope = 'global'
        and rp.effect = 'deny'
    );
end;
$$;
revoke execute on function "app"."authorize"("app"."app_permission", text) from public, anon;
grant execute on function "app"."authorize"("app"."app_permission", text) to authenticated;

alter table "public"."post" enable row level security;
revoke all on table "public"."post" from anon, authenticated;
grant select, insert, update, delete on table "public"."post" to authenticated;

drop policy if exists "post_select" on "public"."post";
create policy "post_select"
  on "public"."post"
  as permissive
  for select
  to authenticated
  using (((select "app".permdock_has('post.read')) or ("orgId" in (select "app".permitted_tenant_ids('post.read')))) or ((select "app".permdock_has('post.list')) or ("orgId" in (select "app".permitted_tenant_ids('post.list')))));

drop policy if exists "post_update" on "public"."post";
create policy "post_update"
  on "public"."post"
  as permissive
  for update
  to authenticated
  using ((select "app".permdock_has('post.update#1')) or (("orgId" in (select "app".permitted_tenant_ids('post.update#2'))) and ("authorId" = (select "app".permdock_user_id()))))
  with check ((select "app".permdock_has('post.update#1')) or (("orgId" in (select "app".permitted_tenant_ids('post.update#2'))) and ("authorId" = (select "app".permdock_user_id()))));

drop policy if exists "post_delete" on "public"."post";
create policy "post_delete"
  on "public"."post"
  as permissive
  for delete
  to authenticated
  using ((select "app".permdock_has('post.delete')));

drop policy if exists "post_insert" on "public"."post";
create policy "post_insert"
  on "public"."post"
  as permissive
  for insert
  to authenticated
  with check ((select "app".permdock_has('post.create')) or ("orgId" in (select "app".permitted_tenant_ids('post.create'))));
