-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- rbac scaffold (Supabase Custom Claims and RBAC)
-- authorize: database (reads user_roles on every statement)
-- the custom access token hook that writes user_role: permdock supabase hook generate
do $$ begin
  create type "public"."app_role" as enum ('admin', 'member');
exception when duplicate_object then null;
end $$;
do $$ begin
  create type "public"."app_permission" as enum ('post.read', 'post.update', 'post.delete', 'post.publish', 'post.archive', 'post.create', 'post.list');
exception when duplicate_object then null;
end $$;

create table if not exists "public"."user_roles" (
  user_id uuid not null references auth.users on delete cascade,
  role "public"."app_role" not null,
  primary key (user_id, role)
);

alter table "public"."user_roles" enable row level security;
revoke all on table "public"."user_roles" from authenticated, anon, public;

-- permdock helpers (database: reads the membership and user_roles tables)
-- policies call them uncorrelated, so Postgres evaluates each once per statement

create table if not exists "public".role_permissions (
  role text not null,
  permission text not null,
  grant_key text not null,
  scope text not null check (scope ~ '^[a-z][a-z0-9_]*$'),
  effect text not null default 'allow' check (effect in ('allow', 'deny')),
  primary key (role, grant_key, scope)
);
alter table "public".role_permissions enable row level security;
revoke all on table "public".role_permissions from anon, authenticated, public;

insert into "public".role_permissions (role, permission, grant_key, scope, effect) values
  ('admin', 'post.read', 'post.read', 'global', 'allow'),
  ('admin', 'post.update', 'post.update#1', 'global', 'allow'),
  ('admin', 'post.delete', 'post.delete', 'global', 'allow'),
  ('admin', 'post.create', 'post.create', 'global', 'allow'),
  ('admin', 'post.list', 'post.list', 'global', 'allow'),
  ('member', 'post.read', 'post.read', 'tenant', 'allow'),
  ('member', 'post.list', 'post.list', 'tenant', 'allow'),
  ('member', 'post.create', 'post.create', 'tenant', 'allow'),
  ('member', 'post.update', 'post.update#2', 'tenant', 'allow')
on conflict (role, grant_key, scope) do update
  set permission = excluded.permission, effect = excluded.effect;
delete from "public".role_permissions
where (role, grant_key, scope) not in (values
  ('admin', 'post.read', 'global'),
  ('admin', 'post.update#1', 'global'),
  ('admin', 'post.delete', 'global'),
  ('admin', 'post.create', 'global'),
  ('admin', 'post.list', 'global'),
  ('member', 'post.read', 'tenant'),
  ('member', 'post.list', 'tenant'),
  ('member', 'post.create', 'tenant'),
  ('member', 'post.update#2', 'tenant')
);

create or replace function "public".permdock_has(p_grant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from "public".user_roles ur
    join "public".role_permissions rp on rp.role = ur.role::text
    where ur.user_id = (select auth.uid())
      and rp.grant_key = p_grant
      and rp.scope = 'global'
  )
$$;
revoke execute on function "public".permdock_has(text) from public, anon;
grant execute on function "public".permdock_has(text) to authenticated;

create or replace function "public".permitted_tenant_ids(p_grant text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select m."organization_id"::uuid
  from "public"."organization_members" m
  join "public".role_permissions rp on rp.role = m."role"::text
  where m."user_id" = (select auth.uid())
    and rp.grant_key = p_grant
    and rp.scope = 'tenant'
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or m."organization_id"::text = nullif(((select auth.jwt()) ->> 'tenant_id'), ''))
$$;
revoke execute on function "public".permitted_tenant_ids(text) from public, anon;
grant execute on function "public".permitted_tenant_ids(text) to authenticated;

create or replace function "public"."authorize"(
  requested_permission "public"."app_permission",
  requested_tenant text default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
begin
  if uid is null then
    return false;
  end if;
  if requested_tenant is not null then
    return exists (
      select 1
      from "public"."organization_members" m
      join "public"."role_permissions" rp on rp.role = m."role"::text
      where m."user_id"::text = uid::text
        and m."organization_id"::text = requested_tenant
        and rp.permission = requested_permission::text
        and rp.scope = 'tenant'
        and rp.effect = 'allow'
    );
  end if;
  return exists (
    select 1
    from "public"."user_roles" ur
    join "public"."role_permissions" rp on rp.role = ur.role::text
    where ur.user_id = uid
      and rp.permission = requested_permission::text
      and rp.scope = 'global'
      and rp.effect = 'allow'
  );
end;
$$;

revoke execute on function "public"."authorize"("public"."app_permission", text) from public, anon;
grant execute on function "public"."authorize"("public"."app_permission", text) to authenticated;

revoke all on table "post" from anon, authenticated;
grant select, insert, update, delete on table "post" to authenticated;
alter table "post" enable row level security;

drop policy if exists "post_select" on "post";
create policy "post_select"
  on "post"
  as permissive
  for select
  to authenticated
  using (((select "public".permdock_has('post.read')) or ("orgId" in (select "public".permitted_tenant_ids('post.read')))) or ((select "public".permdock_has('post.list')) or ("orgId" in (select "public".permitted_tenant_ids('post.list')))));

drop policy if exists "post_update" on "post";
create policy "post_update"
  on "post"
  as permissive
  for update
  to authenticated
  using ((select "public".permdock_has('post.update#1')) or (("orgId" in (select "public".permitted_tenant_ids('post.update#2'))) and ("authorId" = (select auth.uid()))))
  with check ((select "public".permdock_has('post.update#1')) or (("orgId" in (select "public".permitted_tenant_ids('post.update#2'))) and ("authorId" = (select auth.uid()))));

drop policy if exists "post_delete" on "post";
create policy "post_delete"
  on "post"
  as permissive
  for delete
  to authenticated
  using ((select "public".permdock_has('post.delete')));

drop policy if exists "post_insert" on "post";
create policy "post_insert"
  on "post"
  as permissive
  for insert
  to authenticated
  with check ((select "public".permdock_has('post.create')) or ("orgId" in (select "public".permitted_tenant_ids('post.create'))));
