-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- permdock helpers (database: reads the membership and user_roles tables)
-- policies call them uncorrelated, so Postgres evaluates each once per statement

create table if not exists "public".role_permissions (
  role text not null,
  permission text not null,
  grant_key text not null,
  scope text not null check (scope ~ '^[a-z][a-z0-9_]*$'),
  effect text not null default 'allow' check (effect in ('allow', 'deny')),
  primary key (role, grant_key, scope)
);
alter table "public".role_permissions enable row level security;
revoke all on table "public".role_permissions from anon, authenticated, public;

insert into "public".role_permissions (role, permission, grant_key, scope, effect) values
  ('owner', 'staff.read', 'staff.read', 'organization', 'allow'),
  ('owner', 'staff.list', 'staff.list', 'organization', 'allow'),
  ('owner', 'quotes.read', 'quotes.read', 'organization', 'allow'),
  ('owner', 'quotes.list', 'quotes.list', 'organization', 'allow'),
  ('member', 'staff.read', 'staff.read', 'organization', 'allow'),
  ('member', 'staff.list', 'staff.list', 'organization', 'allow'),
  ('contact', 'quotes.read', 'quotes.read', 'customer', 'allow'),
  ('contact', 'quotes.list', 'quotes.list', 'customer', 'allow')
on conflict (role, grant_key, scope) do update
  set permission = excluded.permission, effect = excluded.effect;
delete from "public".role_permissions
where (role, grant_key, scope) not in (values
  ('owner', 'staff.read', 'organization'),
  ('owner', 'staff.list', 'organization'),
  ('owner', 'quotes.read', 'organization'),
  ('owner', 'quotes.list', 'organization'),
  ('member', 'staff.read', 'organization'),
  ('member', 'staff.list', 'organization'),
  ('contact', 'quotes.read', 'customer'),
  ('contact', 'quotes.list', 'customer')
);

create table if not exists "public".user_roles (
  user_id uuid not null references auth.users on delete cascade,
  role text not null,
  primary key (user_id, role)
);
alter table "public".user_roles enable row level security;
revoke all on table "public".user_roles from anon, authenticated, public;

create or replace function "public".permdock_has(p_grant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from "public".user_roles ur
    join "public".role_permissions rp on rp.role = ur.role::text
    where ur.user_id = (select auth.uid())
      and rp.grant_key = p_grant
      and rp.scope = 'global'
  )
$$;
revoke execute on function "public".permdock_has(text) from public, anon;
grant execute on function "public".permdock_has(text) to authenticated;

create or replace function "public".permitted_organization_ids(p_grant text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id"::text = (select auth.uid())::text
    group by m."scope"::text, m."scope_id"::text
  ) ms
  cross join lateral jsonb_array_elements_text(
    case jsonb_typeof(ms.roles) when 'array' then ms.roles else '[]'::jsonb end
  ) r(role)
  join "public".role_permissions rp on rp.role = r.role
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'organization'
    and rp.grant_key = p_grant
    and rp.scope = 'organization'
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or ms.id = nullif(((select auth.jwt()) ->> 'tenant_id'), ''))
$$;
revoke execute on function "public".permitted_organization_ids(text) from public, anon;
grant execute on function "public".permitted_organization_ids(text) to authenticated;

create or replace function "public".member_organization_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id"::text = (select auth.uid())::text
    group by m."scope"::text, m."scope_id"::text
  ) ms
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'organization'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0
$$;
revoke execute on function "public".member_organization_ids() from public, anon;
grant execute on function "public".member_organization_ids() to authenticated;

create or replace function "public".member_organization_ids_for(p_user uuid)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id"::text = p_user::text
    group by m."scope"::text, m."scope_id"::text
  ) ms
  where coalesce(p_user::text, '') <> ''
    and ms.scope = 'organization'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0
$$;
revoke execute on function "public".member_organization_ids_for(uuid) from public, anon, authenticated;

create or replace function "public".permitted_customer_ids(p_grant text)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id"::text = (select auth.uid())::text
    group by m."scope"::text, m."scope_id"::text
    union all
    select 'customer'::text as scope, m."customer_id"::text as id, jsonb_build_object('organization', m."organization_id"::text) as within, jsonb_build_array('contact') as roles, 'contact'::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."contacts" m
    where m."user_id"::text = (select auth.uid())::text
    group by m."customer_id", m."organization_id"
  ) ms
  cross join lateral jsonb_array_elements_text(
    case jsonb_typeof(ms.roles) when 'array' then ms.roles else '[]'::jsonb end
  ) r(role)
  join "public".role_permissions rp on rp.role = r.role
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'customer'
    and rp.grant_key = p_grant
    and rp.scope = 'customer'
    and (nullif(((select auth.jwt()) ->> 'tenant_id'), '') is null or ms.within ->> 'organization' = nullif(((select auth.jwt()) ->> 'tenant_id'), ''))
$$;
revoke execute on function "public".permitted_customer_ids(text) from public, anon;
grant execute on function "public".permitted_customer_ids(text) to authenticated;

create or replace function "public".member_customer_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id"::text = (select auth.uid())::text
    group by m."scope"::text, m."scope_id"::text
    union all
    select 'customer'::text as scope, m."customer_id"::text as id, jsonb_build_object('organization', m."organization_id"::text) as within, jsonb_build_array('contact') as roles, 'contact'::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."contacts" m
    where m."user_id"::text = (select auth.uid())::text
    group by m."customer_id", m."organization_id"
  ) ms
  where coalesce((select auth.uid())::text, '') <> ''
    and ms.scope = 'customer'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0
$$;
revoke execute on function "public".member_customer_ids() from public, anon;
grant execute on function "public".member_customer_ids() to authenticated;

create or replace function "public".member_customer_ids_for(p_user uuid)
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select distinct (ms.id)::uuid
  from (
    select m."scope"::text as scope, m."scope_id"::text as id, null::jsonb as within, jsonb_agg(distinct m."role"::text order by m."role"::text) as roles, null::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."memberships" m
    where m."user_id"::text = p_user::text
    group by m."scope"::text, m."scope_id"::text
    union all
    select 'customer'::text as scope, m."customer_id"::text as id, jsonb_build_object('organization', m."organization_id"::text) as within, jsonb_build_array('contact') as roles, 'contact'::text as via, null::bigint as expires_at, null::text as granted_by, null::text as reason, null::text as member_group, null::text as managed_by, null::jsonb as seats
    from "public"."contacts" m
    where m."user_id"::text = p_user::text
    group by m."customer_id", m."organization_id"
  ) ms
  where coalesce(p_user::text, '') <> ''
    and ms.scope = 'customer'
    and jsonb_typeof(ms.roles) = 'array'
    and jsonb_array_length(ms.roles) > 0
$$;
revoke execute on function "public".member_customer_ids_for(uuid) from public, anon, authenticated;

-- organization: no memberships table configured, so min, max and transferOnly are checked only by decideRoleChange

revoke all on table "staff" from anon, authenticated;
grant select on table "staff" to authenticated;
alter table "staff" enable row level security;

revoke all on table "quotes" from anon, authenticated;
grant select on table "quotes" to authenticated;
alter table "quotes" enable row level security;

drop policy if exists "staff_select" on "staff";
create policy "staff_select"
  on "staff"
  as permissive
  for select
  to authenticated
  using (("organization_id" in (select "public".permitted_organization_ids('staff.read'))) or ("organization_id" in (select "public".permitted_organization_ids('staff.list'))));

drop policy if exists "quotes_select" on "quotes";
create policy "quotes_select"
  on "quotes"
  as permissive
  for select
  to authenticated
  using ((("organization_id" in (select "public".permitted_organization_ids('quotes.read'))) or ("customer_id" in (select "public".permitted_customer_ids('quotes.read')))) or (("organization_id" in (select "public".permitted_organization_ids('quotes.list'))) or ("customer_id" in (select "public".permitted_customer_ids('quotes.list')))));
