import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';

import type { Permission } from '../../src/index.ts';

import { run } from '../../src/cli/run.ts';
import { listPermissions } from '../../src/index.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const TMP = join(HERE, '../../tmp');

const temps: string[] = [];

function workdir(files: Readonly<Record<string, string>>): string {
  mkdirSync(TMP, { recursive: true });
  const dir = mkdtempSync(join(TMP, 'import-'));
  temps.push(dir);
  for (const [name, text] of Object.entries(files)) {
    writeFileSync(join(dir, name), text);
  }
  return dir;
}

afterEach(() => {
  for (const dir of temps.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

async function generated(
  dir: string,
  file: string,
): Promise<readonly Permission[]> {
  const module = (await import(
    `${pathToFileURL(join(dir, file)).href}?t=${Date.now()}`
  )) as { readonly permissions: Parameters<typeof listPermissions>[0] };
  return listPermissions(module.permissions);
}

const SCOPED = {
  openapi: '3.2.0',
  info: { title: 'blog', version: '1' },
  components: {
    securitySchemes: {
      oauth: {
        type: 'oauth2',
        flows: {
          clientCredentials: {
            tokenUrl: 'https://auth.example.com/token',
            scopes: { 'post:read': 'Read', 'post:list': 'List' },
          },
        },
      },
    },
    schemas: {
      Post: {
        type: 'object',
        required: ['id', 'title'],
        properties: {
          id: { type: 'string' },
          title: { type: 'string' },
          views: { type: 'integer' },
          status: { enum: ['draft', 'published'] },
        },
      },
    },
  },
  paths: {
    '/posts': {
      get: {
        summary: 'List posts',
        security: [{ oauth: ['post:list'] }],
        responses: { '200': { description: 'ok' } },
      },
    },
    '/posts/{id}': {
      get: {
        security: [{ oauth: ['post:read'] }],
        'x-vendor-note': 'kept',
        responses: {
          '200': {
            description: 'ok',
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/Post' },
              },
            },
          },
        },
      },
      delete: {
        'x-permdock-permissions': ['post.delete'],
        responses: { '204': { description: 'gone' } },
      },
    },
  },
};

describe('openapi import', () => {
  it('maps scopes and x-permdock-permissions to keys and infers arity', async () => {
    const dir = workdir({ 'openapi.json': JSON.stringify(SCOPED) });
    const result = await run(
      [
        'openapi',
        'import',
        '--doc',
        'openapi.json',
        '--out',
        'permissions.generated.ts',
        '--schema',
        'zod',
      ],
      { cwd: dir },
    );
    expect(result.stdout).toContain('1 resources, 3 permissions');
    expect(result.code).toBe(0);
    const text = readFileSync(join(dir, 'permissions.generated.ts'), 'utf8');
    expect(text).toMatch(/^\/\/ @generated by permdock openapi import/u);
    expect(text).toContain(
      'z.object({ id: z.string(), title: z.string(), views: z.number().int().optional(), status: z.enum(["draft","published"]).optional() })',
    );
    const leaves = await generated(dir, 'permissions.generated.ts');
    expect(
      leaves.map((leaf) => [leaf.key, leaf.kind, leaf.meta.inferredFrom]),
    ).toEqual([
      ['post.delete', 'instance', 'DELETE /posts/{id}'],
      ['post.read', 'instance', 'GET /posts/{id}'],
      ['post.list', 'collection', 'GET /posts'],
    ]);
    expect(leaves.find((leaf) => leaf.key === 'post.list')?.meta).toMatchObject(
      {
        title: 'List posts',
        readOnly: true,
      },
    );
  });

  it('reads YAML, names actions by method and path, and honours --map', async () => {
    const dir = workdir({
      'openapi.yaml': `openapi: 3.1.0
info:
  title: shop
  version: '1'
paths:
  /orders:
    get:
      responses:
        '200': { description: ok }
    post:
      operationId: place-order
      responses:
        '201': { description: created }
  /orders/{orderId}/refund:
    post:
      responses:
        '200': { description: ok }
`,
      'map.json': JSON.stringify({
        'POST /orders/{orderId}/refund': 'billing.order.refund',
      }),
    });
    const result = await run(
      [
        'openapi',
        'import',
        '--doc',
        'openapi.yaml',
        '--out',
        'gen.ts',
        '--map',
        'map.json',
      ],
      { cwd: dir },
    );
    expect(result.code).toBe(0);
    const leaves = await generated(dir, 'gen.ts');
    expect(
      leaves
        .map((leaf) => [leaf.key, leaf.kind])
        .toSorted(([a], [b]) => String(a).localeCompare(String(b))),
    ).toEqual([
      ['billing.order.refund', 'instance'],
      ['orders.list', 'collection'],
      ['orders.placeOrder', 'collection'],
    ]);
  });

  it('rejects a document that is not valid OpenAPI 3.1 or 3.2', async () => {
    const dir = workdir({
      'bad.json': JSON.stringify({ openapi: '3.2.0', paths: {} }),
      'old.json': JSON.stringify({ swagger: '2.0' }),
      'proto.json': JSON.stringify({
        ...SCOPED,
        paths: {
          '/x': { get: { 'x-permdock-permissions': ['__proto__.polluted'] } },
        },
      }),
    });
    const bad = await run(
      ['openapi', 'import', '--doc', 'bad.json', '--out', 'x.ts'],
      { cwd: dir },
    );
    expect(bad.code).toBe(2);
    expect(bad.stdout).toContain('not valid OpenAPI 3.2');
    const old = await run(
      ['openapi', 'import', '--doc', 'old.json', '--out', 'x.ts'],
      { cwd: dir },
    );
    expect(old.code).toBe(2);
    const proto = await run(
      ['openapi', 'import', '--doc', 'proto.json', '--out', 'x.ts'],
      { cwd: dir },
    );
    expect(proto.code).toBe(1);
    expect(proto.stdout).toContain('is not a permission key');
  });

  it('round-trips x-permdock-permissions through --annotate and emit', async () => {
    const dir = workdir({
      'openapi.json': JSON.stringify(SCOPED),
      'permdock.config.ts': `export default { permissions: './gen.ts' };\n`,
    });
    const imported = await run(
      [
        'openapi',
        'import',
        '--doc',
        'openapi.json',
        '--out',
        'gen.ts',
        '--annotate',
      ],
      { cwd: dir },
    );
    expect(imported.code).toBe(0);
    const annotated = JSON.parse(
      readFileSync(join(dir, 'openapi.json'), 'utf8'),
    ) as typeof SCOPED;
    expect(annotated.paths['/posts/{id}'].get).toMatchObject({
      'x-permdock-permissions': ['post.read'],
      'x-vendor-note': 'kept',
    });
    const emitted = await run(
      [
        'openapi',
        'emit',
        '--doc',
        'openapi.json',
        '--out',
        'out.json',
        '--authorization-url',
        'https://auth.example.com/authorize',
        '--token-url',
        'https://auth.example.com/token',
      ],
      { cwd: dir },
    );
    expect(emitted.code).toBe(0);
    const out = JSON.parse(readFileSync(join(dir, 'out.json'), 'utf8')) as {
      paths: Record<string, Record<string, { security?: unknown }>>;
    };
    expect(out.paths['/posts']?.['get']?.security).toEqual([
      { permdockOAuth: ['post:list'] },
    ]);
    const again = await run(
      ['openapi', 'import', '--doc', 'out.json', '--out', 'gen2.ts'],
      { cwd: dir },
    );
    expect(again.code).toBe(0);
    expect(readFileSync(join(dir, 'gen2.ts'), 'utf8')).toBe(
      readFileSync(join(dir, 'gen.ts'), 'utf8'),
    );
  });

  it('keeps YAML comments when annotating', async () => {
    const dir = workdir({
      'openapi.yaml': `# owned by the platform team
openapi: 3.2.0
info: { title: t, version: '1' }
paths:
  /posts/{id}:
    delete:
      x-internal: true # keep me
      responses:
        '204': { description: gone }
`,
    });
    const result = await run(
      [
        'openapi',
        'import',
        '--doc',
        'openapi.yaml',
        '--out',
        'gen.ts',
        '--annotate',
      ],
      { cwd: dir },
    );
    expect(result.code).toBe(0);
    const yaml = readFileSync(join(dir, 'openapi.yaml'), 'utf8');
    expect(yaml).toContain('# owned by the platform team');
    expect(yaml).toContain('x-internal: true # keep me');
    expect(yaml).toContain('x-permdock-permissions:');
    expect(yaml).toContain('- posts.delete');
  });
});
