import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';

import type {
  CatalogDocument,
  CliIo,
  CollectConfig,
  PermDockConfig,
  ScanResult,
} from './types.ts';

import {
  buildCatalog,
  catalogForCompare,
  formatCatalogJson,
} from './catalog-doc.ts';
import { catalogPath } from './catalog-path.ts';
import { defaultSrcPath, listSourceFiles, rel } from './files.ts';
import {
  asPermissionTree,
  leavesOf,
  loadModule,
  pickNamed,
  loadConfiguredPolicy,
} from './load.ts';
import { scanSources } from './scan.ts';

export type CollectOutcome = {
  readonly code: 0 | 1 | 2;
  readonly document: CatalogDocument | undefined;
  readonly scan: ScanResult | undefined;
  readonly outPath: string;
  readonly message: string;
};

export async function runCollect(input: {
  readonly cwd: string;
  readonly config: PermDockConfig;
  readonly collect: CollectConfig;
  readonly check: boolean;
  readonly now: Date;
  readonly io?: CliIo;
}): Promise<CollectOutcome> {
  const srcPath =
    input.collect.srcPath ?? input.config.collect?.srcPath ?? defaultSrcPath();
  const outPath = catalogPath(input.config, input.cwd, input.collect.out);
  const permissionsRel =
    input.config.permissions ?? guessPermissions(input.cwd, srcPath);
  if (permissionsRel === undefined) {
    return {
      code: 2,
      document: undefined,
      scan: undefined,
      outPath,
      message:
        'usage: set permissions in permdock.config.ts or pass a definePermissions module',
    };
  }
  const permissionsAbs = resolve(input.cwd, permissionsRel);
  if (!existsSync(permissionsAbs)) {
    return {
      code: 2,
      document: undefined,
      scan: undefined,
      outPath,
      message: `PermDock CLI: permissions module not found: ${rel(input.cwd, permissionsAbs)}`,
    };
  }
  let tree;
  try {
    const mod = await loadModule(permissionsAbs);
    tree = asPermissionTree(pickNamed(mod, ['permissions']));
  } catch (error) {
    return {
      code: 2,
      document: undefined,
      scan: undefined,
      outPath,
      message: error instanceof Error ? error.message : String(error),
    };
  }
  const files = listSourceFiles(input.cwd, srcPath);
  const knownKeys = new Set(leavesOf(tree).map((leaf) => leaf.key));
  const scan = scanSources(input.cwd, files, knownKeys);
  const document = buildCatalog(
    tree,
    scan,
    input.now.toISOString(),
    await loadConfiguredPolicy(input.cwd, input.config.policy),
  );
  const next = formatCatalogJson(document);
  if (input.check) {
    if (!existsSync(outPath)) {
      return {
        code: 1,
        document,
        scan,
        outPath,
        message: `catalog missing: ${rel(input.cwd, outPath)}`,
      };
    }
    const current = readFileSync(outPath, 'utf8');
    // SAFETY: only serialised again by catalogForCompare; any other shape just compares unequal.
    const currentDoc = JSON.parse(current) as CatalogDocument;
    if (catalogForCompare(currentDoc) !== catalogForCompare(document)) {
      return {
        code: 1,
        document,
        scan,
        outPath,
        message: `catalog drift: ${rel(input.cwd, outPath)}`,
      };
    }
    return {
      code: 0,
      document,
      scan,
      outPath,
      message: `catalog up to date: ${rel(input.cwd, outPath)}`,
    };
  }
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, next);
  const barrel = input.collect.barrel ?? input.config.collect?.barrel;
  if (barrel !== undefined && barrel !== false) {
    const barrelPath = resolve(
      input.cwd,
      barrel === true ? 'src/permissions.generated.ts' : barrel,
    );
    writeBarrel(barrelPath, permissionsAbs);
  }
  return {
    code: 0,
    document,
    scan,
    outPath,
    message: `wrote ${rel(input.cwd, outPath)}`,
  };
}

function guessPermissions(
  cwd: string,
  srcPath: readonly string[],
): string | undefined {
  const candidates = [
    'src/permissions.ts',
    'permissions.ts',
    ...srcPath.map((entry) => `${entry.replace(/\/$/, '')}/permissions.ts`),
  ];
  return candidates.find((file) => existsSync(resolve(cwd, file)));
}

function writeBarrel(abs: string, permissionsAbs: string): void {
  const specifier = relative(dirname(abs), permissionsAbs)
    .replace(/\\/gu, '/')
    .replace(/\.tsx?$/u, '.js');
  const body = `// @generated by permdock — do not edit
import { mergePermissions } from 'permdock'
import { permissions as collected } from '${specifier.startsWith('.') ? specifier : `./${specifier}`}'

export const permissions = mergePermissions(collected)
`;
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, body);
}
