import type { CompiledPolicy, SqlCommand } from './rls-compile.ts';
import type { FieldView } from './rls-fields.ts';
import type { RlsTarget } from './types.ts';

import {
  columnGrantSql,
  columnRevokeSql,
  fieldViewsSql,
  revokeColumnsSql,
} from './rls-fields.ts';
import { quoteIdent, quoteTable } from './rls-sql.ts';

const HEADER =
  '-- generated by permdock rls generate\n-- fail-closed: never target a bypass role\n';

function assertNoServiceRole(text: string): void {
  if (
    /\bto\s+service_role\b|\bfrom\s+service_role\b|\bservice_role\b\s*;/i.test(
      text,
    )
  ) {
    throw new Error('PermDock CLI: generated RLS must never emit service_role');
  }
}

/** `force row level security` for every table a policy targets, so the table owner is not exempt. */
export function forceSql(policies: readonly CompiledPolicy[]): string {
  return [...new Set(policies.map((item) => item.table))]
    .map(
      (table) => `alter table ${quoteTable(table)} force row level security;`,
    )
    .join('\n');
}

function migrationComment(sqlText: string): string[] {
  return sqlText === '' ? [] : ['/* run in a migration:', sqlText, '*/', ''];
}

/** The field views and, for targets without grants, the `--revoke-columns` statements. */
function fieldsMigration(views: readonly FieldView[]): string {
  return [revokeColumnsSql(views), fieldViewsSql(views)]
    .filter((part) => part !== '')
    .join('\n\n');
}

export function emitSql(
  policies: readonly CompiledPolicy[],
  preamble: string,
  force = false,
  views: readonly FieldView[] = [],
): string {
  const tables = [...new Set(policies.map((item) => item.table))];
  const chunks: string[] = [HEADER];
  if (preamble !== '') {
    chunks.push(preamble);
  }
  for (const table of tables) {
    const closed = views.find(
      (view) => view.table === table && view.companion !== undefined,
    );
    chunks.push(
      `revoke all on table ${quoteTable(table)} from anon, authenticated;`,
    );
    for (const role of ['anon', 'authenticated']) {
      const cmds = new Set(
        policies
          .filter(
            (item) =>
              item.table === table &&
              item.effect === 'allow' &&
              item.roles.includes(role),
          )
          .map((item) => item.command),
      );
      const grants = ['select', 'insert', 'update', 'delete'].filter(
        (cmd) =>
          cmds.has(cmd as SqlCommand) &&
          (closed === undefined || cmd !== 'select'),
      );
      if (grants.length > 0) {
        chunks.push(
          `grant ${grants.join(', ')} on table ${quoteTable(table)} to ${role};`,
        );
      }
      if (closed !== undefined && cmds.has('select')) {
        chunks.push(columnGrantSql(closed, role));
      }
    }
    if (closed !== undefined) {
      chunks.push(columnRevokeSql(closed));
    }
    chunks.push(`alter table ${quoteTable(table)} enable row level security;`);
    if (force) {
      chunks.push(`alter table ${quoteTable(table)} force row level security;`);
    }
    chunks.push('');
  }
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const to = item.roles.join(', ');
    const lines = [
      `drop policy if exists ${quoteIdent(item.name)} on ${quoteTable(item.table)};`,
      `create policy ${quoteIdent(item.name)}`,
      `  on ${quoteTable(item.table)}`,
      `  as ${as}`,
      `  for ${item.command}`,
      `  to ${to}`,
    ];
    if (item.using !== undefined) {
      lines.push(`  using (${item.using})`);
    }
    if (item.check !== undefined) {
      lines.push(`  with check (${item.check})`);
    }
    chunks.push(`${lines.join('\n')};\n`);
  }
  if (views.length > 0) {
    chunks.push(fieldViewsSql(views));
  }
  const text = `${chunks.join('\n').trim()}\n`;
  assertNoServiceRole(text);
  return text;
}

function drizzleRoles(roles: readonly string[]): string {
  return roles.includes('anon')
    ? '[anonRole, authenticatedRole]'
    : 'authenticatedRole';
}

export function emitDrizzle(
  policies: readonly CompiledPolicy[],
  preamble: string,
  force = false,
  views: readonly FieldView[] = [],
): string {
  const anon = policies.some((item) => item.roles.includes('anon'));
  const lines = [
    '// generated by permdock rls generate',
    '// fail-closed: never target a bypass role',
    "import { sql } from 'drizzle-orm'",
    `import { ${anon ? 'anonRole, ' : ''}authenticatedRole, pgPolicy } from 'drizzle-orm/pg-core'`,
    '',
  ];
  if (preamble !== '') {
    lines.push('/* run in a migration:', preamble.trim(), '*/', '');
  }
  if (force) {
    lines.push(...migrationComment(forceSql(policies)));
  }
  lines.push(...migrationComment(fieldsMigration(views)));
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const using =
      item.using === undefined ? '' : `\n  using: sql\`${item.using}\`,`;
    const check =
      item.check === undefined ? '' : `\n  withCheck: sql\`${item.check}\`,`;
    lines.push(
      `export const ${item.name} = pgPolicy('${item.name}', {`,
      `  as: '${as}',`,
      `  for: '${item.command}',`,
      `  to: ${drizzleRoles(item.roles)},${using}${check}`,
      '})',
      '',
    );
  }
  const text = `${lines.join('\n')}\n`;
  assertNoServiceRole(text);
  return text;
}

export function emitPrisma(
  policies: readonly CompiledPolicy[],
  preamble: string,
  force = false,
  views: readonly FieldView[] = [],
): string {
  const byTable = new Map<string, CompiledPolicy[]>();
  for (const item of policies) {
    const list = byTable.get(item.table) ?? [];
    list.push(item);
    byTable.set(item.table, list);
  }
  const lines = [
    '// generated by permdock rls generate',
    '// fail-closed: never target a bypass role',
    '',
  ];
  if (preamble !== '') {
    lines.push('/* run in a migration:', preamble.trim(), '*/', '');
  }
  if (force) {
    lines.push(...migrationComment(forceSql(policies)));
  }
  lines.push(...migrationComment(fieldsMigration(views)));
  for (const [table, items] of byTable) {
    const model = table.charAt(0).toUpperCase() + table.slice(1);
    lines.push(`model ${model} {`);
    lines.push('  @@rls');
    for (const item of items) {
      const kind = `policy_${item.command}`;
      lines.push(`  ${kind} ${item.name} {`);
      lines.push(`    roles: [${item.roles.join(', ')}]`);
      if (item.using !== undefined) {
        lines.push(`    using: ${JSON.stringify(item.using)}`);
      }
      if (item.check !== undefined) {
        lines.push(`    withCheck: ${JSON.stringify(item.check)}`);
      }
      lines.push('  }');
    }
    lines.push('}', '');
  }
  const text = `${lines.join('\n')}\n`;
  assertNoServiceRole(text);
  return text;
}

export function defaultOut(target: RlsTarget): string {
  switch (target) {
    case 'sql':
      return 'rls.sql';
    case 'drizzle':
      return 'src/db/policies.ts';
    case 'prisma':
      return 'prisma/policies.prisma';
    default: {
      const exhaustive: never = target;
      return exhaustive;
    }
  }
}
