import type { CompiledPolicy, SqlCommand } from './rls-compile.ts';
import type { FieldView } from './rls-fields.ts';
import type { RlsDialect, RlsTarget } from './types.ts';

import {
  columnGrantSql,
  columnRevokeSql,
  fieldViewsSql,
} from './rls-fields.ts';
import { qualifiedTable, quoteIdent, quoteTable } from './rls-sql.ts';

const HEADER =
  '-- generated by permdock rls generate\n-- fail-closed: never target a bypass role\n';

function assertNoServiceRole(text: string): void {
  if (/\bservice_role\b/iu.test(text)) {
    throw new Error('PermDock CLI: generated RLS must never emit service_role');
  }
}

/**
 * Neon's Data API and `pg_session_jwt` name the anonymous role `anonymous`;
 * Supabase, PostgREST and the GUC pattern use `anon`. Role lists end a line
 * or a statement after `to` or `from`, so only those are renamed.
 */
export function dialectRoles(text: string, dialect: RlsDialect): string {
  if (dialect !== 'neon') {
    return text;
  }
  return text.replaceAll(
    /\b(to|from) ((?:[a-z_]+, )*[a-z_]+)(?=;|\n)/gu,
    (_match, keyword: string, list: string) =>
      `${keyword} ${list
        .split(', ')
        .map((role) => (role === 'anon' ? 'anonymous' : role))
        .join(', ')}`,
  );
}

function tablesOf(policies: readonly CompiledPolicy[]): string[] {
  return [...new Set(policies.map((item) => item.table))];
}

/** Enable (and force) row level security, then the table grants for the commands a policy allows. */
function tableSql(
  table: string,
  policies: readonly CompiledPolicy[],
  force: boolean,
  views: readonly FieldView[],
): string {
  const closed = views.find(
    (view) => view.table === table && view.companion !== undefined,
  );
  const target = quoteTable(qualifiedTable(table));
  const lines = [`alter table ${target} enable row level security;`];
  if (force) {
    lines.push(`alter table ${target} force row level security;`);
  }
  lines.push(`revoke all on table ${target} from anon, authenticated;`);
  for (const role of ['anon', 'authenticated']) {
    const cmds = new Set(
      policies
        .filter(
          (item) =>
            item.table === table &&
            item.effect === 'allow' &&
            item.roles.includes(role),
        )
        .map((item) => item.command),
    );
    // SAFETY: every literal in the list is a SqlCommand.
    const grants = ['select', 'insert', 'update', 'delete'].filter(
      (cmd) =>
        cmds.has(cmd as SqlCommand) &&
        (closed === undefined || cmd !== 'select'),
    );
    if (grants.length > 0) {
      lines.push(`grant ${grants.join(', ')} on table ${target} to ${role};`);
    }
    if (closed !== undefined && cmds.has('select')) {
      lines.push(columnGrantSql(closed, role));
    }
  }
  if (closed !== undefined) {
    lines.push(columnRevokeSql(closed));
  }
  return lines.join('\n');
}

export function emitSql(
  policies: readonly CompiledPolicy[],
  preamble: string,
  force = false,
  views: readonly FieldView[] = [],
): string {
  const chunks: string[] = [HEADER];
  if (preamble !== '') {
    chunks.push(preamble);
  }
  for (const table of tablesOf(policies)) {
    chunks.push(tableSql(table, policies, force, views), '');
  }
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const to = item.roles.join(', ');
    const lines = [
      `drop policy if exists ${quoteIdent(item.name)} on ${quoteTable(qualifiedTable(item.table))};`,
      `create policy ${quoteIdent(item.name)}`,
      `  on ${quoteTable(qualifiedTable(item.table))}`,
      `  as ${as}`,
      `  for ${item.command}`,
      `  to ${to}`,
    ];
    if (item.using !== undefined) {
      lines.push(`  using (${item.using})`);
    }
    if (item.check !== undefined) {
      lines.push(`  with check (${item.check})`);
    }
    chunks.push(`${lines.join('\n')};\n`);
  }
  if (views.length > 0) {
    chunks.push(fieldViewsSql(views));
  }
  const text = `${chunks.join('\n').trim()}\n`;
  assertNoServiceRole(text);
  return text;
}

/**
 * The SQL a Drizzle or Prisma schema cannot declare: helpers, grants, `force` and field views.
 * `rls generate` writes it next to `out` for a custom migration.
 */
export function migrationSql(
  policies: readonly CompiledPolicy[],
  preamble: string,
  force: boolean,
  views: readonly FieldView[],
): string {
  const parts = [
    preamble.trim(),
    ...tablesOf(policies).map((table) =>
      tableSql(table, policies, force, views),
    ),
    fieldViewsSql(views),
  ].filter((part) => part !== '');
  if (parts.length === 0) {
    return '';
  }
  const text = `${HEADER}\n${parts.join('\n\n')}\n`;
  assertNoServiceRole(text);
  return text;
}

function helpersNote(helpers: string | undefined, how: string): string[] {
  return helpers === undefined ? [] : [`// run ${helpers} ${how}`];
}

function camelCase(name: string): string {
  return name.replace(/[_-]+([a-z0-9])/gi, (_, char: string) =>
    char.toUpperCase(),
  );
}

function pascalCase(name: string): string {
  const camel = camelCase(name);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function identifier(name: string, what: string): string {
  if (!IDENTIFIER.test(name)) {
    throw new Error(
      `PermDock CLI: ${what} ${JSON.stringify(name)} is not an identifier`,
    );
  }
  return name;
}

function quoted(text: string): string {
  return `'${text.replace(/[\\']/g, (match) => `\\${match}`)}'`;
}

function templateText(text: string): string {
  return text.replace(/[\\`]|\$\{/g, (match) => `\\${match}`);
}

export type DrizzleEmitOptions = {
  readonly dialect: RlsDialect;
  /** Module exporting the tables, as imported from the output file. */
  readonly schema?: string;
  /** Export name per table name. */
  readonly exports?: Readonly<Record<string, string>>;
  /** File name of the migration SQL written next to the output. */
  readonly helpers?: string;
};

const AUTH_UID = '(select auth.uid())';

function drizzleRoles(list: readonly string[]): string {
  return list.includes('anon')
    ? '[anonRole, authenticatedRole]'
    : 'authenticatedRole';
}

export function emitDrizzle(
  policies: readonly CompiledPolicy[],
  options: DrizzleEmitOptions,
): string {
  const supabase = options.dialect === 'supabase';
  const anon = policies.some((item) => item.roles.includes('anon'));
  const sqlOf = (text: string): string => {
    const parts = text.split(AUTH_UID).map(templateText);
    return `sql\`${supabase ? parts.join('${authUid}') : parts.join(AUTH_UID)}\``;
  };
  const usesUid =
    supabase &&
    policies.some(
      (item) =>
        item.using?.includes(AUTH_UID) === true ||
        item.check?.includes(AUTH_UID) === true,
    );
  const lines = [
    '// generated by permdock rls generate',
    '// fail-closed: never target a bypass role',
    ...helpersNote(
      options.helpers,
      'in a custom migration (drizzle-kit generate --custom)',
    ),
    "import { sql } from 'drizzle-orm'",
  ];
  if (supabase) {
    const named = [
      anon ? 'anonRole' : '',
      'authenticatedRole',
      usesUid ? 'authUid' : '',
    ]
      .filter((name) => name !== '')
      .join(', ');
    lines.push(
      "import { pgPolicy } from 'drizzle-orm/pg-core'",
      `import { ${named} } from 'drizzle-orm/supabase'`,
    );
  } else {
    lines.push("import { pgPolicy, pgRole } from 'drizzle-orm/pg-core'");
  }
  lines.push(
    `import * as schema from ${quoted(options.schema ?? './schema')}`,
    '',
  );
  if (!supabase) {
    if (anon) {
      lines.push(
        `export const anonRole = pgRole('${options.dialect === 'neon' ? 'anonymous' : 'anon'}').existing()`,
      );
    }
    lines.push(
      "export const authenticatedRole = pgRole('authenticated').existing()",
      '',
    );
  }
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const table = identifier(
      options.exports?.[item.table] ?? camelCase(item.table),
      'table export',
    );
    const name = identifier(camelCase(item.name), 'policy export');
    const using =
      item.using === undefined ? '' : `\n  using: ${sqlOf(item.using)},`;
    const check =
      item.check === undefined ? '' : `\n  withCheck: ${sqlOf(item.check)},`;
    lines.push(
      `export const ${name} = pgPolicy(${quoted(item.name)}, {`,
      `  as: '${as}',`,
      `  for: '${item.command}',`,
      `  to: ${drizzleRoles(item.roles)},${using}${check}`,
      `}).link(schema.${table})`,
      '',
    );
  }
  const text = `${lines.join('\n').trimEnd()}\n`;
  assertNoServiceRole(text);
  return text;
}

export type PrismaEmitOptions = {
  /** Model name per table name. */
  readonly models?: Readonly<Record<string, string>>;
  /** File name of the migration SQL written next to the output. */
  readonly helpers?: string;
};

/** Prisma 8 `policy_<command>` blocks; each target model declares `@@rls` itself. */
export function emitPrisma(
  policies: readonly CompiledPolicy[],
  options: PrismaEmitOptions = {},
): string {
  const modelOf = (table: string): string =>
    identifier(options.models?.[table] ?? pascalCase(table), 'model');
  const models = [...new Set(policies.map((item) => modelOf(item.table)))];
  const lines = [
    '// generated by permdock rls generate (Prisma 8 policy blocks)',
    '// fail-closed: never target a bypass role',
    `// add @@rls to ${models.length === 1 ? 'model' : 'models'} ${models.join(', ')}; keep these blocks in their namespace`,
    ...helpersNote(options.helpers, 'in a migration before these policies'),
    '',
  ];
  for (const item of policies) {
    if (item.effect === 'deny') {
      throw new Error(
        `PermDock CLI: Prisma policy blocks are permissive only, so ${item.name} (a deny) needs --target sql`,
      );
    }
    lines.push(
      `policy_${item.command} ${identifier(item.name, 'policy name')} {`,
      `  target = ${modelOf(item.table)}`,
      `  roles  = [${item.roles.join(', ')}]`,
    );
    if (item.using !== undefined) {
      lines.push(`  using  = ${JSON.stringify(item.using)}`);
    }
    if (item.check !== undefined) {
      lines.push(`  withCheck = ${JSON.stringify(item.check)}`);
    }
    lines.push('}', '');
  }
  const text = `${lines.join('\n').trimEnd()}\n`;
  assertNoServiceRole(text);
  return text;
}

/** The migration file written next to `out`. */
export function migrationOut(out: string): string {
  const dot = out.lastIndexOf('.');
  const slash = Math.max(out.lastIndexOf('/'), out.lastIndexOf('\\'));
  return `${dot > slash ? out.slice(0, dot) : out}.migration.sql`;
}

export function defaultOut(target: RlsTarget): string {
  switch (target) {
    case 'sql':
      return 'rls.sql';
    case 'drizzle':
      return 'src/db/policies.ts';
    case 'prisma':
      return 'prisma/policies.prisma';
    default: {
      const exhaustive: never = target;
      return exhaustive;
    }
  }
}
