import type { Condition, Grant, Policy } from 'permdock';

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import type {
  CliIo,
  PermDockConfig,
  RlsDialect,
  RlsMemberships,
  RlsTarget,
} from './types.ts';

import { asPolicy, loadModule, pickNamed } from './load.ts';
import {
  andConditions,
  compileConditionSql,
  parseMembershipsFlag,
  quoteIdent,
  quoteLiteral,
  quoteTable,
  type RlsSqlContext,
} from './rls-sql.ts';

function grantRoleName(grant: Grant): string {
  return grant.role ?? 'grant';
}

export type GenerateOutcome = {
  readonly code: 0 | 1 | 2;
  readonly output: string;
  readonly text: string;
};

type SqlCommand = 'select' | 'insert' | 'update' | 'delete';

type CompiledPolicy = {
  readonly name: string;
  readonly table: string;
  readonly command: SqlCommand;
  readonly effect: 'allow' | 'deny';
  readonly roles: readonly string[];
  readonly using?: string;
  readonly check?: string;
  readonly permissionKey: string;
};

const HEADER =
  '-- generated by permdock rls generate\n-- fail-closed: never target a bypass role\n';

function commandFor(action: string): SqlCommand | undefined {
  switch (action) {
    case 'read':
    case 'list':
    case 'get':
      return 'select';
    case 'create':
      return 'insert';
    case 'update':
      return 'update';
    case 'delete':
      return 'delete';
    default:
      return undefined;
  }
}

function tableFor(
  resource: string,
  tables: Readonly<Record<string, string>> | undefined,
): string {
  return tables?.[resource] ?? resource;
}

function parentFields(policy: Policy, resourceName: string): readonly string[] {
  const fields: string[] = [];
  let current = policy.resources.get(resourceName);
  const seen = new Set<string>();
  while (current?.parent !== undefined) {
    if (seen.has(current.name)) {
      break;
    }
    seen.add(current.name);
    fields.push(current.parent.field);
    current = policy.resources.get(current.parent.resource);
  }
  return fields;
}

function scopeCondition(grant: Grant, policy: Policy): Condition | undefined {
  if (grant.scope === 'global') {
    return undefined;
  }
  if (grant.scope === 'tenant') {
    const field = policy.scopes.tenant?.key;
    if (field === undefined) {
      throw new Error(
        'PermDock CLI: tenant-scoped grant needs definePolicy({ scopes.tenant })',
      );
    }
    return {
      op: 'memberOf',
      scope: 'tenant',
      field,
      roles: grant.role === null ? [] : [grant.role],
    };
  }
  if (grant.scope === 'team') {
    const field = policy.scopes.team?.key;
    if (field === undefined) {
      throw new Error(
        'PermDock CLI: team-scoped grant needs definePolicy({ scopes.team })',
      );
    }
    return {
      op: 'memberOf',
      scope: 'team',
      field,
      roles: grant.role === null ? [] : [grant.role],
    };
  }
  const resourceName = grant.scope.resource;
  const node = policy.resources.get(resourceName);
  return {
    op: 'memberOf',
    scope: 'resource',
    field: node?.id ?? 'id',
    roles: grant.role === null ? [] : [grant.role],
    resource: resourceName,
    parents: parentFields(policy, resourceName),
  };
}

function policyRoles(roleName: string): readonly string[] {
  if (roleName === 'anonymous' || roleName === 'anon') {
    return ['anon', 'authenticated'];
  }
  return ['authenticated'];
}

function policyName(
  role: string,
  resource: string,
  action: string,
  effect: 'allow' | 'deny',
): string {
  const prefix = effect === 'deny' ? 'deny_' : '';
  return `${prefix}${role}_${resource}_${action}`.replaceAll(
    /[^A-Za-z0-9_]/g,
    '_',
  );
}

function compileGrant(
  grant: Grant,
  policy: Policy,
  ctx: RlsSqlContext,
  tables: Readonly<Record<string, string>> | undefined,
  rbac: boolean,
  warnings: string[],
  skipClosures: boolean,
): CompiledPolicy | undefined {
  if (grant.closure !== undefined || grant.portable === false) {
    if (skipClosures) {
      warnings.push(
        `skipped non-portable grant ${grantRoleName(grant)}/${grant.permission.key}`,
      );
      return undefined;
    }
    throw new Error(
      `PermDock CLI: closure grant ${grantRoleName(grant)}/${grant.permission.key} is not portable; rewrite it or pass --skip-closures`,
    );
  }
  if (grant.approval === 'human') {
    warnings.push(
      `skipped approval:human grant ${grantRoleName(grant)}/${grant.permission.key}`,
    );
    return undefined;
  }
  const command = commandFor(grant.permission.action);
  if (command === undefined) {
    warnings.push(
      `skipped ${grant.permission.key}: action is not a SQL command`,
    );
    return undefined;
  }
  const scoped = andConditions(scopeCondition(grant, policy), grant.where);
  const check = grant.check ?? (command === 'update' ? grant.where : undefined);
  let using =
    command === 'insert'
      ? undefined
      : scoped === undefined
        ? 'true'
        : compileConditionSql(scoped, ctx);
  let withCheck =
    command === 'insert' || command === 'update'
      ? check === undefined && scoped === undefined
        ? 'true'
        : compileConditionSql(
            check ?? scoped ?? { op: 'eq', field: '_', value: true },
            ctx,
          )
      : undefined;
  if (command === 'insert' && scoped !== undefined && check === undefined) {
    withCheck = compileConditionSql(scoped, ctx);
  }
  if (rbac) {
    const call = `(select authorize(${quoteLiteral(grant.permission.key)}))`;
    using =
      using === undefined || using === 'true' ? call : `${call} and (${using})`;
    if (withCheck !== undefined) {
      withCheck = withCheck === 'true' ? call : `${call} and (${withCheck})`;
    }
  }
  if (grant.effect === 'deny') {
    if (using !== undefined) {
      using = `not (${using})`;
    }
    if (withCheck !== undefined) {
      withCheck = `not (${withCheck})`;
    }
  }
  return {
    name: policyName(
      grantRoleName(grant),
      grant.permission.resource,
      grant.permission.action,
      grant.effect,
    ),
    table: tableFor(grant.permission.resource, tables),
    command,
    effect: grant.effect,
    roles: policyRoles(grantRoleName(grant)),
    ...(using === undefined ? {} : { using }),
    ...(withCheck === undefined ? {} : { check: withCheck }),
    permissionKey: grant.permission.key,
  };
}

function ensureSelectCoverage(
  policies: CompiledPolicy[],
  warnings: string[],
): CompiledPolicy[] {
  const extra: CompiledPolicy[] = [];
  const seen = new Set(
    policies
      .filter((item) => item.command === 'select')
      .map((item) => `${item.table}:${item.roles.join(',')}`),
  );
  for (const item of policies) {
    if (item.command !== 'update' && item.command !== 'delete') {
      continue;
    }
    const key = `${item.table}:${item.roles.join(',')}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    extra.push({
      name: `${item.name}_select_coverage`,
      table: item.table,
      command: 'select',
      effect: 'allow',
      roles: item.roles,
      using: item.using ?? 'true',
      permissionKey: item.permissionKey,
    });
    warnings.push(
      `added SELECT coverage for ${item.table} (${item.permissionKey})`,
    );
  }
  return [...policies, ...extra];
}

function assertNoServiceRole(text: string): void {
  if (
    /\bto\s+service_role\b|\bfrom\s+service_role\b|\bservice_role\b\s*;/i.test(
      text,
    )
  ) {
    throw new Error('PermDock CLI: generated RLS must never emit service_role');
  }
}

function emitSql(policies: readonly CompiledPolicy[], rbac: string): string {
  const tables = [...new Set(policies.map((item) => item.table))];
  const chunks: string[] = [HEADER];
  if (rbac !== '') {
    chunks.push(rbac);
  }
  for (const table of tables) {
    const cmds = new Set(
      policies
        .filter((item) => item.table === table)
        .map((item) => item.command),
    );
    const grants = ['select', 'insert', 'update', 'delete'].filter((cmd) =>
      cmds.has(cmd as SqlCommand),
    );
    chunks.push(
      `revoke all on table ${quoteTable(table)} from anon, authenticated;`,
    );
    if (grants.length > 0) {
      chunks.push(
        `grant ${grants.join(', ')} on table ${quoteTable(table)} to authenticated;`,
      );
    }
    chunks.push(`alter table ${quoteTable(table)} enable row level security;`);
    chunks.push('');
  }
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const to = item.roles.join(', ');
    const lines = [
      `drop policy if exists ${quoteIdent(item.name)} on ${quoteTable(item.table)};`,
      `create policy ${quoteIdent(item.name)}`,
      `  on ${quoteTable(item.table)}`,
      `  as ${as}`,
      `  for ${item.command}`,
      `  to ${to}`,
    ];
    if (item.using !== undefined) {
      lines.push(`  using (${item.using})`);
    }
    if (item.check !== undefined) {
      lines.push(`  with check (${item.check})`);
    }
    chunks.push(`${lines.join('\n')};\n`);
  }
  const text = `${chunks.join('\n').trim()}\n`;
  assertNoServiceRole(text);
  return text;
}

function emitDrizzle(
  policies: readonly CompiledPolicy[],
  rbac: string,
): string {
  const lines = [
    '// generated by permdock rls generate',
    '// fail-closed: never target a bypass role',
    "import { sql } from 'drizzle-orm'",
    "import { authenticatedRole, pgPolicy } from 'drizzle-orm/pg-core'",
    '',
  ];
  if (rbac !== '') {
    lines.push('/*', rbac.trim(), '*/', '');
  }
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const using =
      item.using === undefined ? '' : `\n  using: sql\`${item.using}\`,`;
    const check =
      item.check === undefined ? '' : `\n  withCheck: sql\`${item.check}\`,`;
    lines.push(
      `export const ${item.name} = pgPolicy('${item.name}', {`,
      `  as: '${as}',`,
      `  for: '${item.command}',`,
      `  to: authenticatedRole,${using}${check}`,
      '})',
      '',
    );
  }
  const text = `${lines.join('\n')}\n`;
  assertNoServiceRole(text);
  return text;
}

function emitPrisma(policies: readonly CompiledPolicy[], rbac: string): string {
  const byTable = new Map<string, CompiledPolicy[]>();
  for (const item of policies) {
    const list = byTable.get(item.table) ?? [];
    list.push(item);
    byTable.set(item.table, list);
  }
  const lines = [
    '// generated by permdock rls generate',
    '// fail-closed: never target a bypass role',
    '',
  ];
  if (rbac !== '') {
    lines.push('/*', rbac.trim(), '*/', '');
  }
  for (const [table, items] of byTable) {
    const model = table.charAt(0).toUpperCase() + table.slice(1);
    lines.push(`model ${model} {`);
    lines.push('  @@rls');
    for (const item of items) {
      const kind = `policy_${item.command}`;
      lines.push(`  ${kind} ${item.name} {`);
      lines.push(`    roles: [${item.roles.join(', ')}]`);
      if (item.using !== undefined) {
        lines.push(`    using: ${JSON.stringify(item.using)}`);
      }
      if (item.check !== undefined) {
        lines.push(`    withCheck: ${JSON.stringify(item.check)}`);
      }
      lines.push('  }');
    }
    lines.push('}', '');
  }
  const text = `${lines.join('\n')}\n`;
  assertNoServiceRole(text);
  return text;
}

function rbacScaffold(policy: Policy): string {
  const permissions = [
    ...new Set(
      policy.roles.flatMap((role) =>
        role.grants.map((grant) => grant.permission.key),
      ),
    ),
  ];
  const roles = policy.roles.map((role) => role.name);
  const permEnum = permissions.map((key) => quoteLiteral(key)).join(', ');
  const roleEnum = roles.map((name) => quoteLiteral(name)).join(', ');
  const seeds: string[] = [];
  for (const role of policy.roles) {
    for (const grant of role.grants) {
      if (grant.effect !== 'allow') {
        continue;
      }
      seeds.push(
        `insert into public.role_permissions (role, permission) values (${quoteLiteral(role.name)}, ${quoteLiteral(grant.permission.key)}) on conflict do nothing;`,
      );
    }
  }
  return `-- rbac scaffold (supabase custom access token hook)
create type public.app_role as enum (${roleEnum});
create type public.app_permission as enum (${permEnum});

create table if not exists public.user_roles (
  user_id uuid primary key,
  role public.app_role not null
);

create table if not exists public.role_permissions (
  role public.app_role not null,
  permission public.app_permission not null,
  primary key (role, permission)
);

${seeds.join('\n')}

create or replace function public.authorize(
  requested_permission public.app_permission,
  requested_tenant uuid default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  binduid uuid;
  user_role public.app_role;
begin
  select (select auth.uid()) into binduid;
  select ur.role into user_role from public.user_roles ur where ur.user_id = binduid;
  if user_role is null then
    return false;
  end if;
  return exists (
    select 1
    from public.role_permissions rp
    where rp.role = user_role
      and rp.permission = requested_permission
  );
end;
$$;

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role into user_role from public.user_roles where user_id = (event ->> 'user_id')::uuid;
  claims := event -> 'claims';
  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;
  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;
`;
}

function defaultOut(target: RlsTarget): string {
  switch (target) {
    case 'sql':
      return 'rls.sql';
    case 'drizzle':
      return 'src/db/policies.ts';
    case 'prisma':
      return 'prisma/policies.prisma';
    default: {
      const exhaustive: never = target;
      return exhaustive;
    }
  }
}

async function loadPolicy(
  cwd: string,
  config: PermDockConfig,
  from: string | undefined,
): Promise<Policy> {
  const policyPath =
    from === 'drizzle' ? config.policy : (from ?? config.policy);
  if (policyPath === undefined) {
    throw new Error(
      'PermDock CLI: rls generate needs policy in permdock.config.ts or --from',
    );
  }
  return asPolicy(
    pickNamed(await loadModule(resolve(cwd, policyPath)), ['policy']),
  );
}

export async function runRlsGenerate(input: {
  readonly cwd: string;
  readonly config: PermDockConfig;
  readonly target: RlsTarget;
  readonly dialect: RlsDialect;
  readonly out?: string;
  readonly from?: string;
  readonly memberships?: string;
  readonly rbac: boolean;
  readonly check: boolean;
  readonly skipClosures: boolean;
  readonly gucPrefix?: string;
  readonly io: CliIo;
}): Promise<GenerateOutcome> {
  const policy = await loadPolicy(input.cwd, input.config, input.from);
  const memberships: RlsMemberships | undefined =
    parseMembershipsFlag(input.memberships) ?? input.config.rls?.memberships;
  const ctx: RlsSqlContext = {
    dialect: input.dialect,
    tenantClaim: input.config.rls?.tenantClaim ?? 'tenant_id',
    gucPrefix: input.gucPrefix ?? input.config.rls?.gucPrefix ?? 'app',
    ...(memberships === undefined ? {} : { memberships }),
  };
  const warnings: string[] = [];
  const compiled: CompiledPolicy[] = [];
  for (const role of policy.roles) {
    for (const grant of role.grants) {
      const item = compileGrant(
        grant,
        policy,
        ctx,
        input.config.rls?.tables,
        input.rbac,
        warnings,
        input.skipClosures,
      );
      if (item !== undefined) {
        compiled.push(item);
      }
    }
  }
  const withSelect = ensureSelectCoverage(compiled, warnings);
  const rbac = input.rbac ? rbacScaffold(policy) : '';
  let text: string;
  switch (input.target) {
    case 'sql':
      text = emitSql(withSelect, rbac);
      break;
    case 'drizzle':
      text = emitDrizzle(withSelect, rbac);
      break;
    case 'prisma':
      text = emitPrisma(withSelect, rbac);
      break;
    default: {
      const exhaustive: never = input.target;
      return exhaustive;
    }
  }
  const columns = new Set<string>();
  for (const role of policy.roles) {
    for (const grant of role.grants) {
      const where = grant.where;
      if (where !== undefined && 'field' in where) {
        columns.add(
          `${tableFor(grant.permission.resource, input.config.rls?.tables)}.${where.field}`,
        );
      }
    }
  }
  for (const column of columns) {
    warnings.push(`index suggestion: create index on ${column}`);
  }
  const outRel = input.out ?? input.config.rls?.out ?? defaultOut(input.target);
  const outPath = resolve(input.cwd, outRel);
  if (input.check) {
    if (!existsSync(outPath)) {
      return {
        code: 1,
        output: `rls generate drift: missing ${outRel}`,
        text,
      };
    }
    if (readFileSync(outPath, 'utf8') === text) {
      return { code: 0, output: 'rls generate up to date', text };
    }
    return { code: 1, output: 'rls generate drift', text };
  }
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, text);
  const extra = warnings.length === 0 ? '' : `\n${warnings.join('\n')}`;
  return { code: 0, output: `wrote ${outRel}${extra}`, text };
}
