import type { Policy } from 'permdock';

import type { CompiledPolicy, SqlCommand } from './rls-compile.ts';
import type { RlsTarget } from './types.ts';

import { quoteIdent, quoteLiteral, quoteTable } from './rls-sql.ts';

const HEADER =
  '-- generated by permdock rls generate\n-- fail-closed: never target a bypass role\n';

function assertNoServiceRole(text: string): void {
  if (
    /\bto\s+service_role\b|\bfrom\s+service_role\b|\bservice_role\b\s*;/i.test(
      text,
    )
  ) {
    throw new Error('PermDock CLI: generated RLS must never emit service_role');
  }
}

export function emitSql(
  policies: readonly CompiledPolicy[],
  rbac: string,
): string {
  const tables = [...new Set(policies.map((item) => item.table))];
  const chunks: string[] = [HEADER];
  if (rbac !== '') {
    chunks.push(rbac);
  }
  for (const table of tables) {
    const cmds = new Set(
      policies
        .filter((item) => item.table === table)
        .map((item) => item.command),
    );
    const grants = ['select', 'insert', 'update', 'delete'].filter((cmd) =>
      cmds.has(cmd as SqlCommand),
    );
    chunks.push(
      `revoke all on table ${quoteTable(table)} from anon, authenticated;`,
    );
    if (grants.length > 0) {
      chunks.push(
        `grant ${grants.join(', ')} on table ${quoteTable(table)} to authenticated;`,
      );
    }
    chunks.push(`alter table ${quoteTable(table)} enable row level security;`);
    chunks.push('');
  }
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const to = item.roles.join(', ');
    const lines = [
      `drop policy if exists ${quoteIdent(item.name)} on ${quoteTable(item.table)};`,
      `create policy ${quoteIdent(item.name)}`,
      `  on ${quoteTable(item.table)}`,
      `  as ${as}`,
      `  for ${item.command}`,
      `  to ${to}`,
    ];
    if (item.using !== undefined) {
      lines.push(`  using (${item.using})`);
    }
    if (item.check !== undefined) {
      lines.push(`  with check (${item.check})`);
    }
    chunks.push(`${lines.join('\n')};\n`);
  }
  const text = `${chunks.join('\n').trim()}\n`;
  assertNoServiceRole(text);
  return text;
}

export function emitDrizzle(
  policies: readonly CompiledPolicy[],
  rbac: string,
): string {
  const lines = [
    '// generated by permdock rls generate',
    '// fail-closed: never target a bypass role',
    "import { sql } from 'drizzle-orm'",
    "import { authenticatedRole, pgPolicy } from 'drizzle-orm/pg-core'",
    '',
  ];
  if (rbac !== '') {
    lines.push('/*', rbac.trim(), '*/', '');
  }
  for (const item of policies) {
    const as = item.effect === 'deny' ? 'restrictive' : 'permissive';
    const using =
      item.using === undefined ? '' : `\n  using: sql\`${item.using}\`,`;
    const check =
      item.check === undefined ? '' : `\n  withCheck: sql\`${item.check}\`,`;
    lines.push(
      `export const ${item.name} = pgPolicy('${item.name}', {`,
      `  as: '${as}',`,
      `  for: '${item.command}',`,
      `  to: authenticatedRole,${using}${check}`,
      '})',
      '',
    );
  }
  const text = `${lines.join('\n')}\n`;
  assertNoServiceRole(text);
  return text;
}

export function emitPrisma(
  policies: readonly CompiledPolicy[],
  rbac: string,
): string {
  const byTable = new Map<string, CompiledPolicy[]>();
  for (const item of policies) {
    const list = byTable.get(item.table) ?? [];
    list.push(item);
    byTable.set(item.table, list);
  }
  const lines = [
    '// generated by permdock rls generate',
    '// fail-closed: never target a bypass role',
    '',
  ];
  if (rbac !== '') {
    lines.push('/*', rbac.trim(), '*/', '');
  }
  for (const [table, items] of byTable) {
    const model = table.charAt(0).toUpperCase() + table.slice(1);
    lines.push(`model ${model} {`);
    lines.push('  @@rls');
    for (const item of items) {
      const kind = `policy_${item.command}`;
      lines.push(`  ${kind} ${item.name} {`);
      lines.push(`    roles: [${item.roles.join(', ')}]`);
      if (item.using !== undefined) {
        lines.push(`    using: ${JSON.stringify(item.using)}`);
      }
      if (item.check !== undefined) {
        lines.push(`    withCheck: ${JSON.stringify(item.check)}`);
      }
      lines.push('  }');
    }
    lines.push('}', '');
  }
  const text = `${lines.join('\n')}\n`;
  assertNoServiceRole(text);
  return text;
}

export function rbacScaffold(policy: Policy): string {
  const permissions = [
    ...new Set(
      policy.roles.flatMap((role) =>
        role.grants.map((grant) => grant.permission.key),
      ),
    ),
  ];
  const roles = policy.roles.map((role) => role.name);
  const permEnum = permissions.map((key) => quoteLiteral(key)).join(', ');
  const roleEnum = roles.map((name) => quoteLiteral(name)).join(', ');
  const seeds: string[] = [];
  for (const role of policy.roles) {
    for (const grant of role.grants) {
      if (grant.effect !== 'allow') {
        continue;
      }
      seeds.push(
        `insert into public.role_permissions (role, permission) values (${quoteLiteral(role.name)}, ${quoteLiteral(grant.permission.key)}) on conflict do nothing;`,
      );
    }
  }
  return `-- rbac scaffold (supabase custom access token hook)
create type public.app_role as enum (${roleEnum});
create type public.app_permission as enum (${permEnum});

create table if not exists public.user_roles (
  user_id uuid primary key,
  role public.app_role not null
);

create table if not exists public.role_permissions (
  role public.app_role not null,
  permission public.app_permission not null,
  primary key (role, permission)
);

${seeds.join('\n')}

create or replace function public.authorize(
  requested_permission public.app_permission,
  requested_tenant uuid default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  binduid uuid;
  user_role public.app_role;
begin
  select (select auth.uid()) into binduid;
  select ur.role into user_role from public.user_roles ur where ur.user_id = binduid;
  if user_role is null then
    return false;
  end if;
  return exists (
    select 1
    from public.role_permissions rp
    where rp.role = user_role
      and rp.permission = requested_permission
  );
end;
$$;

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role into user_role from public.user_roles where user_id = (event ->> 'user_id')::uuid;
  claims := event -> 'claims';
  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;
  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;
`;
}

export function defaultOut(target: RlsTarget): string {
  switch (target) {
    case 'sql':
      return 'rls.sql';
    case 'drizzle':
      return 'src/db/policies.ts';
    case 'prisma':
      return 'prisma/policies.prisma';
    default: {
      const exhaustive: never = target;
      return exhaustive;
    }
  }
}
