// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
/* oxlint-disable */
/* eslint-disable */

import type { SchemaMeta } from "better-supabase";

declare const meta: SchemaMeta;
export default meta;
