// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
// @ts-self-types="./generated.meta.d.ts"
/* oxlint-disable */
/* eslint-disable */

export default {
  "version": 1,
  "casing": "snake",
  "tables": {
    "contacts": {
      "key": "contacts",
      "name": "contacts",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "customer_id": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "user_id": {
          "db": "user_id",
          "type": "uuid",
          "nullable": true,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "contacts_customer_id_fkey",
          "columns": [
            "customer_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "contacts_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "customers": {
      "key": "customers",
      "name": "customers",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "contacts": {
          "table": "contacts",
          "kind": "many",
          "nullable": true,
          "foreignKey": "contacts_customer_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "customer_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customers_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "quotes": {
          "table": "quotes",
          "kind": "many",
          "nullable": true,
          "foreignKey": "quotes_customer_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "customer_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "datetime_preferences": {
      "key": "datetime_preferences",
      "name": "datetime_preferences",
      "schema": "public",
      "kind": "table",
      "columns": {
        "user_id": {
          "db": "user_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "timezone": {
          "db": "timezone",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "week_start": {
          "db": "week_start",
          "type": "text",
          "nullable": false,
          "hasDefault": false,
          "enum": [
            "monday",
            "sunday"
          ]
        },
        "date_format": {
          "db": "date_format",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "time_format": {
          "db": "time_format",
          "type": "text",
          "nullable": false,
          "hasDefault": false,
          "enum": [
            "12h",
            "24h"
          ]
        }
      },
      "primaryKey": [
        "user_id"
      ],
      "uniqueKeys": {},
      "relations": {},
      "flags": {}
    },
    "memberships": {
      "key": "memberships",
      "name": "memberships",
      "schema": "public",
      "kind": "table",
      "columns": {
        "user_id": {
          "db": "user_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "scope": {
          "db": "scope",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "scope_id": {
          "db": "scope_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "role": {
          "db": "role",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "user_id",
        "scope",
        "scope_id",
        "role"
      ],
      "uniqueKeys": {},
      "relations": {},
      "flags": {}
    },
    "organization_features": {
      "key": "organization_features",
      "name": "organization_features",
      "schema": "public",
      "kind": "table",
      "columns": {
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "feature": {
          "db": "feature",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "organization_id",
        "feature"
      ],
      "uniqueKeys": {},
      "relations": {
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "organization_features_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "organizations": {
      "key": "organizations",
      "name": "organizations",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "slug": {
          "db": "slug",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "organizations_slug_key": [
          "slug"
        ]
      },
      "relations": {
        "contacts": {
          "table": "contacts",
          "kind": "many",
          "nullable": true,
          "foreignKey": "contacts_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "customers": {
          "table": "customers",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customers_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "organization_features": {
          "table": "organization_features",
          "kind": "many",
          "nullable": true,
          "foreignKey": "organization_features_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "quotes": {
          "table": "quotes",
          "kind": "many",
          "nullable": true,
          "foreignKey": "quotes_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "staff": {
          "table": "staff",
          "kind": "many",
          "nullable": true,
          "foreignKey": "staff_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "permdock_authz_version": {
      "key": "permdock_authz_version",
      "name": "permdock_authz_version",
      "schema": "public",
      "kind": "table",
      "columns": {
        "user_id": {
          "db": "user_id",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "version": {
          "db": "version",
          "type": "int8",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "user_id"
      ],
      "uniqueKeys": {},
      "relations": {},
      "flags": {}
    },
    "quotes": {
      "key": "quotes",
      "name": "quotes",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "customer_id": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "title": {
          "db": "title",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "amount": {
          "db": "amount",
          "type": "numeric",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "quotes_customer_id_fkey",
          "columns": [
            "customer_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "quotes_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "role_permissions": {
      "key": "role_permissions",
      "name": "role_permissions",
      "schema": "public",
      "kind": "table",
      "columns": {
        "role": {
          "db": "role",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "permission": {
          "db": "permission",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "grant_key": {
          "db": "grant_key",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "scope": {
          "db": "scope",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "effect": {
          "db": "effect",
          "type": "text",
          "nullable": false,
          "hasDefault": true,
          "enum": [
            "allow",
            "deny"
          ]
        }
      },
      "primaryKey": [
        "role",
        "grant_key",
        "scope"
      ],
      "uniqueKeys": {},
      "relations": {},
      "flags": {}
    },
    "staff": {
      "key": "staff",
      "name": "staff",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "user_id": {
          "db": "user_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "title": {
          "db": "title",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "staff_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "user_roles": {
      "key": "user_roles",
      "name": "user_roles",
      "schema": "public",
      "kind": "table",
      "columns": {
        "user_id": {
          "db": "user_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "role": {
          "db": "role",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "user_id",
        "role"
      ],
      "uniqueKeys": {},
      "relations": {},
      "flags": {}
    }
  },
  "enums": {},
  "functions": {
    "custom_access_token_hook": {
      "name": "custom_access_token_hook",
      "schema": "public",
      "args": [
        {
          "name": "event",
          "type": "jsonb"
        }
      ],
      "returns": "jsonb",
      "returnsSet": false,
      "volatility": "stable"
    },
    "datetime_preference_claims": {
      "name": "datetime_preference_claims",
      "schema": "public",
      "args": [
        {
          "name": "p_user_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "returnsSet": false,
      "volatility": "stable"
    },
    "feature_claims": {
      "name": "feature_claims",
      "schema": "public",
      "args": [
        {
          "name": "p_user_id",
          "type": "uuid"
        }
      ],
      "returns": "jsonb",
      "returnsSet": false,
      "volatility": "stable"
    },
    "member_customer_ids": {
      "name": "member_customer_ids",
      "schema": "public",
      "args": [],
      "returns": "uuid",
      "returnsSet": true,
      "volatility": "stable"
    },
    "member_customer_ids_for": {
      "name": "member_customer_ids_for",
      "schema": "public",
      "args": [
        {
          "name": "p_user",
          "type": "uuid"
        }
      ],
      "returns": "uuid",
      "returnsSet": true,
      "volatility": "stable"
    },
    "member_organization_ids": {
      "name": "member_organization_ids",
      "schema": "public",
      "args": [],
      "returns": "uuid",
      "returnsSet": true,
      "volatility": "stable"
    },
    "member_organization_ids_for": {
      "name": "member_organization_ids_for",
      "schema": "public",
      "args": [
        {
          "name": "p_user",
          "type": "uuid"
        }
      ],
      "returns": "uuid",
      "returnsSet": true,
      "volatility": "stable"
    },
    "permdock_has": {
      "name": "permdock_has",
      "schema": "public",
      "args": [
        {
          "name": "p_grant",
          "type": "text"
        }
      ],
      "returns": "bool",
      "returnsSet": false,
      "volatility": "stable"
    },
    "permitted_customer_ids": {
      "name": "permitted_customer_ids",
      "schema": "public",
      "args": [
        {
          "name": "p_grant",
          "type": "text"
        }
      ],
      "returns": "uuid",
      "returnsSet": true,
      "volatility": "stable"
    },
    "permitted_organization_ids": {
      "name": "permitted_organization_ids",
      "schema": "public",
      "args": [
        {
          "name": "p_grant",
          "type": "text"
        }
      ],
      "returns": "uuid",
      "returnsSet": true,
      "volatility": "stable"
    }
  }
};
