// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
/* oxlint-disable */
/* eslint-disable */

import { defineSchema, type Schema } from "better-supabase";
import type { EnrichDatabase } from "better-supabase";
import type { Database as SupabaseDatabase } from "./database.types.ts";
import meta from "./generated.meta.js";

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = EnrichDatabase<
  SupabaseDatabase,
  {
    public: {
      datetime_preferences: {
        week_start: "monday" | "sunday";
        time_format: "12h" | "24h";
      };
    };
  }
>;

export const datetime_preferencesWeekStartValues = ["monday", "sunday"] as const;
export type DatetimePreferencesWeekStart = (typeof datetime_preferencesWeekStartValues)[number];
export const datetime_preferencesTimeFormatValues = ["12h", "24h"] as const;
export type DatetimePreferencesTimeFormat = (typeof datetime_preferencesTimeFormatValues)[number];
export type Models = {
  contacts: {
    Row: {
      id: string;
      organization_id: string;
      customer_id: string;
      user_id: string | null;
      name: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      customer_id: string;
      user_id?: string | null;
      name: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      customer_id?: string;
      user_id?: string | null;
      name?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "contacts_customer_id_fkey" | "contacts_organization_id_fkey" | "contacts_user_id_fkey";
    Flags: Record<never, never>;
  };
  customers: {
    Row: {
      id: string;
      organization_id: string;
      name: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      name: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      name?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      contacts: { table: "contacts"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      quotes: { table: "quotes"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "customers_organization_id_fkey";
    Flags: Record<never, never>;
  };
  datetime_preferences: {
    Row: {
      user_id: string;
      timezone: string;
      week_start: "monday" | "sunday";
      date_format: string;
      time_format: "12h" | "24h";
      created_at: string;
      updated_at: string;
    };
    Insert: {
      user_id: string;
      timezone: string;
      week_start: "monday" | "sunday";
      date_format: string;
      time_format: "12h" | "24h";
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      user_id?: string;
      timezone?: string;
      week_start?: "monday" | "sunday";
      date_format?: string;
      time_format?: "12h" | "24h";
      created_at?: string;
      updated_at?: string;
    };
    Relations: Record<never, never>;
    PrimaryKey: "user_id";
    UniqueKeys: Record<never, never>;
    Checks: "datetime_preferences_time_format_check" | "datetime_preferences_week_start_check";
    ForeignKeys: "datetime_preferences_user_id_fkey";
    Flags: Record<never, never>;
  };
  memberships: {
    Row: {
      user_id: string;
      scope: string;
      scope_id: string;
      role: string;
      created_at: string;
    };
    Insert: {
      user_id: string;
      scope: string;
      scope_id: string;
      role: string;
      created_at?: string;
    };
    Update: {
      user_id?: string;
      scope?: string;
      scope_id?: string;
      role?: string;
      created_at?: string;
    };
    Relations: Record<never, never>;
    PrimaryKey: "user_id" | "scope" | "scope_id" | "role";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "memberships_user_id_fkey";
    Flags: Record<never, never>;
  };
  organization_features: {
    Row: {
      organization_id: string;
      feature: string;
      created_at: string;
    };
    Insert: {
      organization_id: string;
      feature: string;
      created_at?: string;
    };
    Update: {
      organization_id?: string;
      feature?: string;
      created_at?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "organization_id" | "feature";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "organization_features_organization_id_fkey";
    Flags: Record<never, never>;
  };
  organizations: {
    Row: {
      id: string;
      slug: string;
      name: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      slug: string;
      name: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      slug?: string;
      name?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      contacts: { table: "contacts"; kind: "many"; nullable: true };
      customers: { table: "customers"; kind: "many"; nullable: true };
      organization_features: { table: "organization_features"; kind: "many"; nullable: true };
      quotes: { table: "quotes"; kind: "many"; nullable: true };
      staff: { table: "staff"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      organizations_slug_key: readonly ["slug"];
    };
    Checks: never;
    ForeignKeys: never;
    Flags: Record<never, never>;
  };
  quotes: {
    Row: {
      id: string;
      organization_id: string;
      customer_id: string;
      title: string;
      amount_minor: number;
      currency: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      customer_id: string;
      title: string;
      amount_minor: number;
      currency: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      customer_id?: string;
      title?: string;
      amount_minor?: number;
      currency?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: "quotes_amount_minor_check" | "quotes_currency_check";
    ForeignKeys: "quotes_customer_id_fkey" | "quotes_organization_id_fkey";
    Flags: Record<never, never>;
  };
  staff: {
    Row: {
      id: string;
      organization_id: string;
      user_id: string;
      name: string;
      title: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      user_id: string;
      name: string;
      title: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      user_id?: string;
      name?: string;
      title?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "staff_organization_id_fkey" | "staff_user_id_fkey";
    Flags: Record<never, never>;
  };
};

export type Functions = {
  audit_retention: {
    Args: {
      tenant: string;
    };
    Returns: string;
  };
  datetime_preference_claims: {
    Args: {
      p_user_id: string;
    };
    Returns: Json;
  };
  feature_claims: {
    Args: {
      p_user_id: string;
    };
    Returns: Json;
  };
};

export type TableName = keyof Models;
/** Constraint names for `isConflict`, `isCheck` and `isForeignKey`. */
export type UniqueConstraint = { [T in TableName]: Extract<keyof Models[T]['UniqueKeys'], string> }[TableName];
export type CheckConstraint = Models[TableName]['Checks'];
export type ForeignKeyConstraint = Models[TableName]['ForeignKeys'];
export type RowOf<T extends TableName> = Models[T]['Row'];
export type InsertOf<T extends TableName> = Models[T]['Insert'];
export type UpdateOf<T extends TableName> = Models[T]['Update'];

export const schema: Schema<Models, Database, Functions> = defineSchema(meta);
