-- generated by permdock rls generate
-- fail-closed: never target a bypass role

alter table "public"."staff" enable row level security;
revoke all on table "public"."staff" from anon, authenticated;
grant select on table "public"."staff" to authenticated;

alter table "public"."quotes" enable row level security;
revoke all on table "public"."quotes" from anon, authenticated;
grant select, update on table "public"."quotes" to authenticated;

drop policy if exists "staff_select" on "public"."staff";
create policy "staff_select"
  on "public"."staff"
  as permissive
  for select
  to authenticated
  using (("organization_id" in (select "permdock".permitted_organization_ids('staff.read'))) or ("organization_id" in (select "permdock".permitted_organization_ids('staff.list'))));

drop policy if exists "quotes_select" on "public"."quotes";
create policy "quotes_select"
  on "public"."quotes"
  as permissive
  for select
  to authenticated
  using ((("organization_id" in (select "permdock".permitted_organization_ids('quotes.read'))) or ("customer_id" in (select "permdock".permitted_customer_ids('quotes.read')))) or (("organization_id" in (select "permdock".permitted_organization_ids('quotes.list'))) or ("customer_id" in (select "permdock".permitted_customer_ids('quotes.list')))));

drop policy if exists "quotes_update" on "public"."quotes";
create policy "quotes_update"
  on "public"."quotes"
  as permissive
  for update
  to authenticated
  using ("organization_id" in (select "permdock".permitted_organization_ids('quotes.update')))
  with check ("organization_id" in (select "permdock".permitted_organization_ids('quotes.update')));

drop policy if exists "quotes_update_read_only_actors" on "public"."quotes";
create policy "quotes_update_read_only_actors"
  on "public"."quotes"
  as restrictive
  for update
  to authenticated
  using (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false))
  with check (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false));
