-- generated by permdock rls generate
-- fail-closed: never target a bypass role

alter table "public"."staff" enable row level security;
revoke all on table "public"."staff" from anon, authenticated;
grant select on table "public"."staff" to authenticated;

alter table "public"."quotes" enable row level security;
revoke all on table "public"."quotes" from anon, authenticated;
grant select, update on table "public"."quotes" to authenticated;

drop policy if exists "staff_select" on "public"."staff";
create policy "staff_select"
  on "public"."staff"
  as permissive
  for select
  to authenticated
  using (("organization_id" in (select "permdock".permitted_organization_ids('staff.read'))) or ("organization_id" in (select "permdock".permitted_organization_ids('staff.list'))));

drop policy if exists "quotes_select" on "public"."quotes";
create policy "quotes_select"
  on "public"."quotes"
  as permissive
  for select
  to authenticated
  using ((("organization_id" in (select "permdock".permitted_organization_ids('quotes.read'))) or ("customer_id" in (select "permdock".permitted_customer_ids('quotes.read')))) or (("organization_id" in (select "permdock".permitted_organization_ids('quotes.list'))) or ("customer_id" in (select "permdock".permitted_customer_ids('quotes.list')))));

drop policy if exists "quotes_update" on "public"."quotes";
create policy "quotes_update"
  on "public"."quotes"
  as permissive
  for update
  to authenticated
  using ("organization_id" in (select "permdock".permitted_organization_ids('quotes.update')))
  with check ("organization_id" in (select "permdock".permitted_organization_ids('quotes.update')));

drop policy if exists "quotes_update_read_only_actors" on "public"."quotes";
create policy "quotes_update_read_only_actors"
  on "public"."quotes"
  as restrictive
  for update
  to authenticated
  using (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false))
  with check (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false));

-- Supabase Realtime and Storage: rls.realtime and rls.storage. RLS on both tables is Supabase's.
drop policy if exists "permdock_realtime_org_organization_quotes_select" on "realtime"."messages";
create policy "permdock_realtime_org_organization_quotes_select"
  on "realtime"."messages"
  as permissive
  for select
  to authenticated
  using (extension in ('broadcast', 'presence')
    and (select realtime.topic()) ~ '^org:[^:]+:quotes$'
    and split_part((select realtime.topic()), ':', 2) in (select x::text from "permdock".permitted_organization_ids('quotes.read') x));

drop policy if exists "permdock_realtime_org_organization_quotes_insert" on "realtime"."messages";
create policy "permdock_realtime_org_organization_quotes_insert"
  on "realtime"."messages"
  as permissive
  for insert
  to authenticated
  with check (extension in ('broadcast', 'presence')
    and (select realtime.topic()) ~ '^org:[^:]+:quotes$'
    and split_part((select realtime.topic()), ':', 2) in (select x::text from "permdock".permitted_organization_ids('quotes.update') x));

drop policy if exists "permdock_storage_quote_files_select" on "storage"."objects";
create policy "permdock_storage_quote_files_select"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
  using (bucket_id = 'quote-files'
    and (storage.foldername(name))[1] in (select x::text from "permdock".permitted_organization_ids('quotes.read') x));

drop policy if exists "permdock_storage_quote_files_insert" on "storage"."objects";
create policy "permdock_storage_quote_files_insert"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
  with check (bucket_id = 'quote-files'
    and (storage.foldername(name))[1] in (select x::text from "permdock".permitted_organization_ids('quotes.update') x));

drop policy if exists "permdock_storage_quote_files_update" on "storage"."objects";
create policy "permdock_storage_quote_files_update"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
  using (bucket_id = 'quote-files'
    and (storage.foldername(name))[1] in (select x::text from "permdock".permitted_organization_ids('quotes.update') x))
  with check (bucket_id = 'quote-files'
    and (storage.foldername(name))[1] in (select x::text from "permdock".permitted_organization_ids('quotes.update') x));

drop policy if exists "permdock_storage_quote_files_delete" on "storage"."objects";
create policy "permdock_storage_quote_files_delete"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
  using (bucket_id = 'quote-files'
    and (storage.foldername(name))[1] in (select x::text from "permdock".permitted_organization_ids('quotes.update') x));

drop policy if exists "realtime_messages_insert_read_only_actors" on "realtime"."messages";
create policy "realtime_messages_insert_read_only_actors"
  on "realtime"."messages"
  as restrictive
  for insert
  to authenticated
  with check (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false));

drop policy if exists "storage_objects_insert_read_only_actors" on "storage"."objects";
create policy "storage_objects_insert_read_only_actors"
  on "storage"."objects"
  as restrictive
  for insert
  to authenticated
  with check (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false));

drop policy if exists "storage_objects_update_read_only_actors" on "storage"."objects";
create policy "storage_objects_update_read_only_actors"
  on "storage"."objects"
  as restrictive
  for update
  to authenticated
  using (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false))
  with check (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false));

drop policy if exists "storage_objects_delete_read_only_actors" on "storage"."objects";
create policy "storage_objects_delete_read_only_actors"
  on "storage"."objects"
  as restrictive
  for delete
  to authenticated
  using (not coalesce((((select auth.jwt()) -> 'act') ->> 'kind') = any(array['support', 'impersonation']::text[]) or ((((select auth.jwt()) -> 'act') ->> 'kind') is null and ((select auth.jwt()) -> 'act') ? 'session_id'), false) or coalesce((((select auth.jwt()) -> 'act') ->> 'read_only') = 'false', false));
