-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- permdock helpers (database: reads the membership and user_roles tables)
-- policies call them uncorrelated, so Postgres evaluates each once per statement

create schema if not exists "permdock";
revoke all on schema "permdock" from public;
grant usage on schema "permdock" to authenticated;

create table if not exists "permdock".role_permissions (
  role text not null,
  permission text not null,
  grant_key text not null,
  scope text not null check (scope ~ '^[a-z][a-z0-9_]*$'),
  effect text not null default 'allow' check (effect in ('allow', 'deny')),
  primary key (role, grant_key, scope)
);
alter table "permdock".role_permissions enable row level security;
revoke all on table "permdock".role_permissions from anon, authenticated, public;

insert into "permdock".role_permissions (role, permission, grant_key, scope, effect) values
  ('primary', 'payment.approve', 'payment.approve', 'org', 'allow'),
  ('approver', 'payment.read', 'payment.read', 'org', 'allow')
on conflict (role, grant_key, scope) do update
  set permission = excluded.permission, effect = excluded.effect;
delete from "permdock".role_permissions
where (role, grant_key, scope) not in (values
  ('primary', 'payment.approve', 'org'),
  ('approver', 'payment.read', 'org')
);

create table if not exists "permdock".user_roles (
  user_id text not null,
  role text not null,
  primary key (user_id, role)
);
alter table "permdock".user_roles enable row level security;
revoke all on table "permdock".user_roles from anon, authenticated, public;

create or replace function "permdock".permdock_has(p_grant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from "permdock".user_roles ur
    join "permdock".role_permissions rp on rp.role = ur.role::text
    where ur.user_id = (select current_setting('app.user_id', true))
      and rp.grant_key = p_grant
      and rp.scope = 'global'
      and not (ur.role::text = any(array['reviewer']::text[]))
  )
$$;
revoke execute on function "permdock".permdock_has(text) from public, anon;
grant execute on function "permdock".permdock_has(text) to authenticated;

create or replace function "permdock".permitted_org_ids(p_grant text)
returns setof text
language sql
stable
security definer
set search_path = ''
as $$
  select m."org_id"::text
  from "public"."org_members" m
  join "public"."org_roles" mk on mk."id" = m."role_id"
  join "permdock".role_permissions rp on rp.role = mk."key"::text
  where m."user_id" = (select current_setting('app.user_id', true))
    and rp.grant_key = p_grant
    and rp.scope = 'org'
    and case mk."key"::text when 'reviewer' then coalesce(null::text, '') = any(array['staff']::text[]) else true end
    and (nullif((select current_setting('app.tenant_id', true)), '') is null or m."org_id"::text = nullif((select current_setting('app.tenant_id', true)), ''))
$$;
revoke execute on function "permdock".permitted_org_ids(text) from public, anon;
grant execute on function "permdock".permitted_org_ids(text) to authenticated;

create or replace function "permdock".member_org_ids()
returns setof text
language sql
stable
security definer
set search_path = ''
as $$
  select distinct m."org_id"::text
  from "public"."org_members" m
  join "public"."org_roles" mk on mk."id" = m."role_id"
  where m."user_id" = (select current_setting('app.user_id', true))
    and mk."key"::text is not null
$$;
revoke execute on function "permdock".member_org_ids() from public, anon;
grant execute on function "permdock".member_org_ids() to authenticated;

-- org: holder counts (min / max), checked at commit
create or replace function "permdock".permdock_holders_org()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ids text[] := '{}';
  v_id text;
  v_key "public"."org_members"."org_id"%type;
  v_total bigint;
  v_count bigint;
begin
  if tg_op in ('UPDATE', 'DELETE') then
    v_ids := v_ids || old."org_id"::text;
  end if;
  if tg_op in ('INSERT', 'UPDATE') then
    v_ids := v_ids || new."org_id"::text;
  end if;
  foreach v_id in array v_ids loop
    continue when v_id is null;
    v_key := v_id;
    select count(*) into v_total from "public"."org_members" m where m."org_id" = v_key;
    select count(distinct m."user_id") into v_count
      from "public"."org_members" m
      join "public"."org_roles" mk on mk."id" = m."role_id"
      where m."org_id" = v_key
        and mk."key"::text = 'primary';
    if v_total > 0 and v_count < 1 then
      raise exception using
        errcode = '23514',
        message = 'permdock: org ' || v_id || ' keeps at least 1 primary',
        hint = 'last-holder';
    end if;
    if v_count > 1 then
      raise exception using
        errcode = '23514',
        message = 'permdock: org ' || v_id || ' has at most 1 primary',
        hint = 'max-holders';
    end if;
    select count(*) into v_total from "public"."org_members" m where m."org_id" = v_key;
    select count(distinct m."user_id") into v_count
      from "public"."org_members" m
      join "public"."org_roles" mk on mk."id" = m."role_id"
      where m."org_id" = v_key
        and mk."key"::text = 'approver';
    if v_count > 2 then
      raise exception using
        errcode = '23514',
        message = 'permdock: org ' || v_id || ' has at most 2 approver',
        hint = 'max-holders';
    end if;
  end loop;
  return null;
end;
$$;
drop trigger if exists "permdock_holders_org" on "public"."org_members";
create constraint trigger "permdock_holders_org"
  after insert or update or delete on "public"."org_members"
  deferrable initially deferred
  for each row execute function "permdock".permdock_holders_org();

-- org: transfer-only roles (primary) keep their holder count per statement
create or replace function "permdock".permdock_transfer_only_org()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_change record;
  v_after bigint;
begin
  if tg_op = 'INSERT' then
    for v_change in
      select c.id, c.role, sum(c.delta) as delta
      from (select n."org_id" as id, nk."key"::text as role, 1 as delta from permdock_new n join "public"."org_roles" nk on nk."id" = n."role_id" where nk."key"::text = any(array['primary']::text[])) c
      group by c.id, c.role
    loop
      continue when v_change.delta = 0 or v_change.id is null;
      select count(distinct m."user_id") into v_after
      from "public"."org_members" m
      join "public"."org_roles" mk on mk."id" = m."role_id"
      where m."org_id" = v_change.id
        and mk."key"::text = v_change.role
        and case v_change.role when 'reviewer' then coalesce(null::text, '') = any(array['staff']::text[]) else true end;
      if v_after > 0 and v_after - v_change.delta > 0 then
        raise exception using
          errcode = '23514',
          message = 'permdock: ' || v_change.role || ' in org ' || v_change.id || ' moves only by transfer',
          hint = 'transfer-only';
      end if;
    end loop;
  elsif tg_op = 'DELETE' then
    for v_change in
      select c.id, c.role, sum(c.delta) as delta
      from (select o."org_id" as id, ok."key"::text as role, -1 as delta from permdock_old o join "public"."org_roles" ok on ok."id" = o."role_id" where ok."key"::text = any(array['primary']::text[])) c
      group by c.id, c.role
    loop
      continue when v_change.delta = 0 or v_change.id is null;
      select count(distinct m."user_id") into v_after
      from "public"."org_members" m
      join "public"."org_roles" mk on mk."id" = m."role_id"
      where m."org_id" = v_change.id
        and mk."key"::text = v_change.role
        and case v_change.role when 'reviewer' then coalesce(null::text, '') = any(array['staff']::text[]) else true end;
      if v_after > 0 and v_after - v_change.delta > 0 then
        raise exception using
          errcode = '23514',
          message = 'permdock: ' || v_change.role || ' in org ' || v_change.id || ' moves only by transfer',
          hint = 'transfer-only';
      end if;
    end loop;
  else
    for v_change in
      select c.id, c.role, sum(c.delta) as delta
      from (select n."org_id" as id, nk."key"::text as role, 1 as delta from permdock_new n join "public"."org_roles" nk on nk."id" = n."role_id" where nk."key"::text = any(array['primary']::text[]) union all select o."org_id" as id, ok."key"::text as role, -1 as delta from permdock_old o join "public"."org_roles" ok on ok."id" = o."role_id" where ok."key"::text = any(array['primary']::text[])) c
      group by c.id, c.role
    loop
      continue when v_change.delta = 0 or v_change.id is null;
      select count(distinct m."user_id") into v_after
      from "public"."org_members" m
      join "public"."org_roles" mk on mk."id" = m."role_id"
      where m."org_id" = v_change.id
        and mk."key"::text = v_change.role
        and case v_change.role when 'reviewer' then coalesce(null::text, '') = any(array['staff']::text[]) else true end;
      if v_after > 0 and v_after - v_change.delta > 0 then
        raise exception using
          errcode = '23514',
          message = 'permdock: ' || v_change.role || ' in org ' || v_change.id || ' moves only by transfer',
          hint = 'transfer-only';
      end if;
    end loop;
  end if;
  return null;
end;
$$;
drop trigger if exists "permdock_transfer_only_org_insert" on "public"."org_members";
create trigger "permdock_transfer_only_org_insert"
  after insert on "public"."org_members"
  referencing new table as permdock_new
  for each statement execute function "permdock".permdock_transfer_only_org();
drop trigger if exists "permdock_transfer_only_org_update" on "public"."org_members";
create trigger "permdock_transfer_only_org_update"
  after update on "public"."org_members"
  referencing old table as permdock_old new table as permdock_new
  for each statement execute function "permdock".permdock_transfer_only_org();
drop trigger if exists "permdock_transfer_only_org_delete" on "public"."org_members";
create trigger "permdock_transfer_only_org_delete"
  after delete on "public"."org_members"
  referencing old table as permdock_old
  for each statement execute function "permdock".permdock_transfer_only_org();

-- who may assign: a held role whose assigns lists p_role, in instance p_scope_id (its scope or an ancestor's)
create or replace function "permdock".permdock_can_assign(p_role text, p_scope_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select current_setting('app.user_id', true))::text, '') <> '' and (
    exists (
      select 1 from "public"."org_members" m
      join "public"."org_roles" mk on mk."id" = m."role_id"
      where m."user_id" = (select current_setting('app.user_id', true))
        and m."org_id"::text = p_scope_id
        and (mk."key"::text, p_role) in (values ('primary', 'primary'), ('primary', 'approver'))
        and case mk."key"::text when 'reviewer' then coalesce(null::text, '') = any(array['staff']::text[]) else true end
    )
  )
$$;
revoke execute on function "permdock".permdock_can_assign(text, text) from public, anon;
grant execute on function "permdock".permdock_can_assign(text, text) to authenticated;

alter table "public"."payment" enable row level security;
revoke all on table "public"."payment" from anon, authenticated;
grant select on table "public"."payment" to authenticated;

alter table "public"."ledger" enable row level security;
revoke all on table "public"."ledger" from anon, authenticated;
grant select on table "public"."ledger" to authenticated;

drop policy if exists "payment_select" on "public"."payment";
create policy "payment_select"
  on "public"."payment"
  as permissive
  for select
  to authenticated
  using ("org_id" in (select "permdock".permitted_org_ids('payment.read')));

drop policy if exists "ledger_select" on "public"."ledger";
create policy "ledger_select"
  on "public"."ledger"
  as permissive
  for select
  to authenticated
  using (exists (select 1 from "ledger_members" m join "public"."org_roles" mk on mk."id" = m."role_id" where m."ledger_id" = "id" and m."user_id" = (select current_setting('app.user_id', true)) and mk."key"::text = any('{reviewer}') and coalesce(m."via"::text, '') = any(array['staff']::text[])));
