import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],
    typecheck: {
      enabled: true,
      include: ['src/**/*.test-d.ts'],
      ignoreSourceErrors: true,
    },
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.test.ts',
        'src/**/*.test-d.ts',
        'src/**/index.ts',
        'src/fixtures/**',
        'src/jwt/**',
        'src/react/**',
        'src/next/**',
        'src/server/**',
        'src/hono/**',
        'src/ai-sdk/**',
        'src/claude-agent/**',
        'src/eve/**',
        'src/openai/**',
        'src/agent/**',
        'src/scim/**',
        'src/cloud/**',
        'src/drizzle/**',
        'src/prisma/**',
        'src/kysely/**',
        'src/supabase/**',
        'src/ssf/**',
        'src/react-native/**',
        'src/express/**',
        'src/fastify/**',
        'src/elysia/**',
        'src/nest/**',
        'src/node/**',
        'src/trpc/**',
        'src/orpc/**',
        'src/vue/**',
        'src/svelte/**',
        'src/solid/**',
        'src/mcp/**',
        'src/authzen/**',
        'src/openapi/**',
        'src/terminal/**',
        'src/webmcp/**',
        'src/a2a/**',
        'src/otel/**',
        'src/core/from-snapshot.ts',
      ],
      thresholds: {
        statements: 95,
        lines: 95,
        functions: 95,
        branches: 93,
      },
    },
  },
});
