-- generated by permdock rls generate
-- fail-closed: never target a bypass role

-- rbac scaffold (supabase custom access token hook)
create type public.app_role as enum ('staff', 'admin', 'member');
create type public.app_permission as enum ('post.read', 'post.list', 'post.create', 'post.update', 'post.delete');

create table if not exists public.user_roles (
  user_id uuid primary key,
  role public.app_role not null
);

create table if not exists public.role_permissions (
  role public.app_role not null,
  permission public.app_permission not null,
  primary key (role, permission)
);

insert into public.role_permissions (role, permission) values ('staff', 'post.read') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('staff', 'post.list') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('admin', 'post.read') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('admin', 'post.list') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('admin', 'post.create') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('admin', 'post.update') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('admin', 'post.delete') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('member', 'post.read') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('member', 'post.list') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('member', 'post.create') on conflict do nothing;
insert into public.role_permissions (role, permission) values ('member', 'post.update') on conflict do nothing;

create or replace function public.authorize(
  requested_permission public.app_permission,
  requested_tenant uuid default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  binduid uuid;
  user_role public.app_role;
begin
  select (select auth.uid()) into binduid;
  select ur.role into user_role from public.user_roles ur where ur.user_id = binduid;
  if user_role is null then
    return false;
  end if;
  return exists (
    select 1
    from public.role_permissions rp
    where rp.role = user_role
      and rp.permission = requested_permission
  );
end;
$$;

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role into user_role from public.user_roles where user_id = (event ->> 'user_id')::uuid;
  claims := event -> 'claims';
  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;
  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;

revoke all on table "post" from anon, authenticated;
grant select, insert, update, delete on table "post" to authenticated;
alter table "post" enable row level security;

drop policy if exists "staff_post_read" on "post";
create policy "staff_post_read"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select authorize('post.read')));

drop policy if exists "staff_post_list" on "post";
create policy "staff_post_list"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select authorize('post.list')));

drop policy if exists "admin_post_read" on "post";
create policy "admin_post_read"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select authorize('post.read')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{admin}'))));

drop policy if exists "admin_post_list" on "post";
create policy "admin_post_list"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select authorize('post.list')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{admin}'))));

drop policy if exists "admin_post_create" on "post";
create policy "admin_post_create"
  on "post"
  as permissive
  for insert
  to authenticated
  using ((select authorize('post.create')))
  with check ((select authorize('post.create')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{admin}'))));

drop policy if exists "admin_post_update" on "post";
create policy "admin_post_update"
  on "post"
  as permissive
  for update
  to authenticated
  using ((select authorize('post.update')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{admin}'))))
  with check ((select authorize('post.update')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{admin}'))));

drop policy if exists "admin_post_delete" on "post";
create policy "admin_post_delete"
  on "post"
  as permissive
  for delete
  to authenticated
  using ((select authorize('post.delete')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{admin}'))));

drop policy if exists "member_post_read" on "post";
create policy "member_post_read"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select authorize('post.read')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}'))));

drop policy if exists "member_post_list" on "post";
create policy "member_post_list"
  on "post"
  as permissive
  for select
  to authenticated
  using ((select authorize('post.list')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}'))));

drop policy if exists "member_post_create" on "post";
create policy "member_post_create"
  on "post"
  as permissive
  for insert
  to authenticated
  using ((select authorize('post.create')))
  with check ((select authorize('post.create')) and (exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}'))));

drop policy if exists "member_post_update" on "post";
create policy "member_post_update"
  on "post"
  as permissive
  for update
  to authenticated
  using ((select authorize('post.update')) and ((exists (select 1 from "organization_members" m where m."organization_id" = "orgId" and m."user_id" = (select auth.uid()) and m."role" = any('{member}')) and "authorId" = (select auth.uid()))))
  with check ((select authorize('post.update')) and ("authorId" = (select auth.uid())));
